// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountSession = `-- name: AccountSession :one
SELECT s.auth_time FROM sessions s
WHERE s.id = $1 AND s.user_id = $2 AND s.id IN (SELECT l.id FROM live_sessions l)
`

type AccountSessionParams struct {
	ID     string
	UserID string
}

// The live Session an account center request comes from.
func (q *Queries) AccountSession(ctx context.Context, arg AccountSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, accountSession, arg.ID, arg.UserID)
	var auth_time pgtype.Timestamptz
	err := row.Scan(&auth_time)
	return auth_time, err
}

const accountUser = `-- name: AccountUser :one
SELECT u.created_at,
       COALESCE((SELECT json_agg(json_build_object('kind', i.kind, 'value', i.value) ORDER BY i.kind)
                 FROM identifiers i WHERE i.user_id = u.id), '[]')::jsonb AS identifiers,
       EXISTS (SELECT 1 FROM passwords p WHERE p.user_id = u.id) AS has_password,
       -- The password login setting lets this User use a password.
       (s.password_login = 'all' OR s.password_login = 'admins' AND EXISTS (
           SELECT 1 FROM user_roles r WHERE r.user_id = u.id AND r.api = 'urn:stars-auth:management-api'))::boolean AS password_allowed,
       -- When 两步验证 was turned on; null while it is off.
       (SELECT t.confirmed_at FROM totp_credentials t WHERE t.user_id = u.id) AS two_factor_since,
       (SELECT count(*) FROM recovery_codes c WHERE c.user_id = u.id AND c.used_at IS NULL) AS recovery_codes_left
FROM users u, settings s
WHERE u.id = $1
`

type AccountUserRow struct {
	CreatedAt         pgtype.Timestamptz
	Identifiers       []byte
	HasPassword       bool
	PasswordAllowed   bool
	TwoFactorSince    pgtype.Timestamptz
	RecoveryCodesLeft int64
}

func (q *Queries) AccountUser(ctx context.Context, id string) (AccountUserRow, error) {
	row := q.db.QueryRow(ctx, accountUser, id)
	var i AccountUserRow
	err := row.Scan(
		&i.CreatedAt,
		&i.Identifiers,
		&i.HasPassword,
		&i.PasswordAllowed,
		&i.TwoFactorSince,
		&i.RecoveryCodesLeft,
	)
	return i, err
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Serialises changes to a User's login paths.
func (q *Queries) LockUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const loginPaths = `-- name: LoginPaths :one
SELECT COALESCE(array_agg(kind ORDER BY kind) FILTER (WHERE kind IS NOT NULL), '{}')::text[] AS identifiers,
       EXISTS (SELECT 1 FROM passwords p WHERE p.user_id = $1) AS has_password
FROM identifiers WHERE user_id = $1
`

type LoginPathsRow struct {
	Identifiers []string
	HasPassword bool
}

// What a User could sign in with (docs/spec/identity.md#不变式).
func (q *Queries) LoginPaths(ctx context.Context, userID string) (LoginPathsRow, error) {
	row := q.db.QueryRow(ctx, loginPaths, userID)
	var i LoginPathsRow
	err := row.Scan(&i.Identifiers, &i.HasPassword)
	return i, err
}

const mustKeepTwoFactor = `-- name: MustKeepTwoFactor :one
SELECT (s.admins_need_two_factor AND EXISTS (
    SELECT 1 FROM user_roles r WHERE r.user_id = $1 AND r.api = 'urn:stars-auth:management-api'))::boolean AS must
FROM settings s
`

// 管理员必须启用两步验证 is on and the User holds a Management API Role.
func (q *Queries) MustKeepTwoFactor(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, mustKeepTwoFactor, userID)
	var must bool
	err := row.Scan(&must)
	return must, err
}

const putPassword = `-- name: PutPassword :exec
WITH put AS (
    INSERT INTO passwords (user_id, hash) VALUES ($1, $2)
    ON CONFLICT (user_id) DO UPDATE SET hash = EXCLUDED.hash
)
INSERT INTO audit_log (event, sub, detail)
VALUES ('password.changed', $1::text, jsonb_build_object('by', $1::text))
`

type PutPasswordParams struct {
	UserID string
	Hash   string
}

// Audited as done by the User.
func (q *Queries) PutPassword(ctx context.Context, arg PutPasswordParams) error {
	_, err := q.db.Exec(ctx, putPassword, arg.UserID, arg.Hash)
	return err
}

const reauthenticate = `-- name: Reauthenticate :exec
UPDATE sessions SET auth_time = now(), amr = $1 WHERE id = $2 AND user_id = $3
`

type ReauthenticateParams struct {
	Amr    []string
	ID     string
	UserID string
}

// The User proved themselves again in this Session.
func (q *Queries) Reauthenticate(ctx context.Context, arg ReauthenticateParams) error {
	_, err := q.db.Exec(ctx, reauthenticate, arg.Amr, arg.ID, arg.UserID)
	return err
}

const removeIdentifier = `-- name: RemoveIdentifier :execrows
WITH gone AS (
    DELETE FROM identifiers WHERE user_id = $2 AND kind = $1 RETURNING user_id
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'identifier.removed', gone.user_id, jsonb_build_object('kind', $1::text, 'by', gone.user_id) FROM gone
`

type RemoveIdentifierParams struct {
	Kind   string
	UserID string
}

// Audited as done by the User.
func (q *Queries) RemoveIdentifier(ctx context.Context, arg RemoveIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeIdentifier, arg.Kind, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removePassword = `-- name: RemovePassword :execrows
WITH gone AS (
    DELETE FROM passwords WHERE user_id = $1 RETURNING user_id
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'password.removed', gone.user_id, jsonb_build_object('by', gone.user_id) FROM gone
`

// Audited as done by the User.
func (q *Queries) RemovePassword(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, removePassword, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userAudit = `-- name: UserAudit :many
SELECT at, event, detail FROM audit_log WHERE sub = $1 ORDER BY id
`

type UserAuditRow struct {
	At     pgtype.Timestamptz
	Event  string
	Detail []byte
}

// The audit events about a User, oldest first.
func (q *Queries) UserAudit(ctx context.Context, sub pgtype.Text) ([]UserAuditRow, error) {
	rows, err := q.db.Query(ctx, userAudit, sub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAuditRow
	for rows.Next() {
		var i UserAuditRow
		if err := rows.Scan(&i.At, &i.Event, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userConsents = `-- name: UserConsents :many
SELECT version, client_id, at FROM consents WHERE user_id = $1 ORDER BY at
`

type UserConsentsRow struct {
	Version  string
	ClientID string
	At       pgtype.Timestamptz
}

func (q *Queries) UserConsents(ctx context.Context, userID string) ([]UserConsentsRow, error) {
	rows, err := q.db.Query(ctx, userConsents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserConsentsRow
	for rows.Next() {
		var i UserConsentsRow
		if err := rows.Scan(&i.Version, &i.ClientID, &i.At); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
