// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const audit = `-- name: Audit :exec
INSERT INTO audit_log (event, sub, detail) VALUES ($1, $2, $3)
`

type AuditParams struct {
	Event  string
	Sub    pgtype.Text
	Detail []byte
}

func (q *Queries) Audit(ctx context.Context, arg AuditParams) error {
	_, err := q.db.Exec(ctx, audit, arg.Event, arg.Sub, arg.Detail)
	return err
}

const auditedSince = `-- name: AuditedSince :one
SELECT EXISTS (SELECT 1 FROM audit_log WHERE event = $1 AND at > $2)
`

type AuditedSinceParams struct {
	Event string
	At    pgtype.Timestamptz
}

func (q *Queries) AuditedSince(ctx context.Context, arg AuditedSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, auditedSince, arg.Event, arg.At)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteOldAudit = `-- name: DeleteOldAudit :exec
DELETE FROM audit_log WHERE at < now() - make_interval(days => (SELECT audit_retention_days FROM settings))
`

func (q *Queries) DeleteOldAudit(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldAudit)
	return err
}
