// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelSecrets = `-- name: ChannelSecrets :many
SELECT field, value FROM channel_secrets WHERE kind = $1
`

type ChannelSecretsRow struct {
	Field string
	Value []byte
}

func (q *Queries) ChannelSecrets(ctx context.Context, kind string) ([]ChannelSecretsRow, error) {
	rows, err := q.db.Query(ctx, channelSecrets, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSecretsRow
	for rows.Next() {
		var i ChannelSecretsRow
		if err := rows.Scan(&i.Field, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE kind = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, deleteChannel, kind)
	return err
}

const deleteChannelSecrets = `-- name: DeleteChannelSecrets :exec
DELETE FROM channel_secrets WHERE kind = $1
`

func (q *Queries) DeleteChannelSecrets(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, deleteChannelSecrets, kind)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT plugin, config FROM channels WHERE kind = $1
`

type GetChannelRow struct {
	Plugin string
	Config []byte
}

func (q *Queries) GetChannel(ctx context.Context, kind string) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, kind)
	var i GetChannelRow
	err := row.Scan(&i.Plugin, &i.Config)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT c.kind, c.plugin, c.config, c.updated_at,
       COALESCE((SELECT jsonb_object_agg(s.field, s.updated_at) FROM channel_secrets s WHERE s.kind = c.kind),
                '{}')::jsonb AS secrets
FROM channels c
ORDER BY c.kind
`

type ListChannelsRow struct {
	Kind      string
	Plugin    string
	Config    []byte
	UpdatedAt pgtype.Timestamptz
	Secrets   []byte
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Plugin,
			&i.Config,
			&i.UpdatedAt,
			&i.Secrets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannels = `-- name: LockChannels :exec
LOCK TABLE channels IN SHARE ROW EXCLUSIVE MODE
`

// Serialises writers, including two first saves of a kind (no row to lock yet).
func (q *Queries) LockChannels(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockChannels)
	return err
}

const putChannel = `-- name: PutChannel :exec
INSERT INTO channels (kind, plugin, config) VALUES ($1, $2, $3)
ON CONFLICT (kind) DO UPDATE SET plugin = excluded.plugin, config = excluded.config, updated_at = now()
`

type PutChannelParams struct {
	Kind   string
	Plugin string
	Config []byte
}

func (q *Queries) PutChannel(ctx context.Context, arg PutChannelParams) error {
	_, err := q.db.Exec(ctx, putChannel, arg.Kind, arg.Plugin, arg.Config)
	return err
}

const putChannelSecret = `-- name: PutChannelSecret :exec
INSERT INTO channel_secrets (kind, field, value) VALUES ($1, $2, $3)
ON CONFLICT (kind, field) DO UPDATE SET value = excluded.value, updated_at = now()
`

type PutChannelSecretParams struct {
	Kind  string
	Field string
	Value []byte
}

func (q *Queries) PutChannelSecret(ctx context.Context, arg PutChannelSecretParams) error {
	_, err := q.db.Exec(ctx, putChannelSecret, arg.Kind, arg.Field, arg.Value)
	return err
}
