// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIdentifier = `-- name: AddIdentifier :exec
INSERT INTO identifiers (user_id, kind, value) VALUES ($1, $2, $3)
`

type AddIdentifierParams struct {
	UserID string
	Kind   string
	Value  string
}

func (q *Queries) AddIdentifier(ctx context.Context, arg AddIdentifierParams) error {
	_, err := q.db.Exec(ctx, addIdentifier, arg.UserID, arg.Kind, arg.Value)
	return err
}

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, api, role) VALUES ($1, $2, $3)
`

type AssignRoleParams struct {
	UserID string
	Api    string
	Role   string
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.Api, arg.Role)
	return err
}

const closeSetup = `-- name: CloseSetup :exec
UPDATE settings SET setup_token = NULL, setup_done = true
`

func (q *Queries) CloseSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, closeSetup)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, user_id, auth_time, amr) VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	IDHash   []byte
	UserID   string
	AuthTime pgtype.Timestamptz
	Amr      []string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.IDHash,
		arg.UserID,
		arg.AuthTime,
		arg.Amr,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}

const deleteIdleSessions = `-- name: DeleteIdleSessions :exec
DELETE FROM sessions WHERE last_seen_at < $1
`

func (q *Queries) DeleteIdleSessions(ctx context.Context, idleSince pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteIdleSessions, idleSince)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, idHash)
	return err
}

const lockSetup = `-- name: LockSetup :one
SELECT setup_token, setup_done FROM settings FOR UPDATE
`

type LockSetupRow struct {
	SetupToken []byte
	SetupDone  bool
}

func (q *Queries) LockSetup(ctx context.Context) (LockSetupRow, error) {
	row := q.db.QueryRow(ctx, lockSetup)
	var i LockSetupRow
	err := row.Scan(&i.SetupToken, &i.SetupDone)
	return i, err
}

const passwordByIdentifier = `-- name: PasswordByIdentifier :one
SELECT i.user_id, p.hash,
       EXISTS (SELECT 1 FROM user_roles r
               WHERE r.user_id = i.user_id AND r.api = 'urn:stars-auth:management-api') AS admin
FROM identifiers i JOIN passwords p USING (user_id)
WHERE i.value = $1
`

type PasswordByIdentifierRow struct {
	UserID string
	Hash   string
	Admin  bool
}

func (q *Queries) PasswordByIdentifier(ctx context.Context, value string) (PasswordByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, passwordByIdentifier, value)
	var i PasswordByIdentifierRow
	err := row.Scan(&i.UserID, &i.Hash, &i.Admin)
	return i, err
}

const passwordLogin = `-- name: PasswordLogin :one
SELECT password_login FROM settings
`

func (q *Queries) PasswordLogin(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, passwordLogin)
	var password_login string
	err := row.Scan(&password_login)
	return password_login, err
}

const setPassword = `-- name: SetPassword :exec
INSERT INTO passwords (user_id, hash) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET hash = EXCLUDED.hash
`

type SetPasswordParams struct {
	UserID string
	Hash   string
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.UserID, arg.Hash)
	return err
}

const setSetupToken = `-- name: SetSetupToken :exec
UPDATE settings SET setup_token = $1
`

func (q *Queries) SetSetupToken(ctx context.Context, setupToken []byte) error {
	_, err := q.db.Exec(ctx, setSetupToken, setupToken)
	return err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions SET last_seen_at = now()
WHERE id_hash = $1 AND last_seen_at > $2
RETURNING user_id, auth_time, amr
`

type TouchSessionParams struct {
	IDHash    []byte
	IdleSince pgtype.Timestamptz
}

type TouchSessionRow struct {
	UserID   string
	AuthTime pgtype.Timestamptz
	Amr      []string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (TouchSessionRow, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.IDHash, arg.IdleSince)
	var i TouchSessionRow
	err := row.Scan(&i.UserID, &i.AuthTime, &i.Amr)
	return i, err
}
