// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
)

const addIdentifier = `-- name: AddIdentifier :exec
INSERT INTO identifiers (user_id, kind, value) VALUES ($1, $2, $3)
`

type AddIdentifierParams struct {
	UserID string
	Kind   string
	Value  string
}

func (q *Queries) AddIdentifier(ctx context.Context, arg AddIdentifierParams) error {
	_, err := q.db.Exec(ctx, addIdentifier, arg.UserID, arg.Kind, arg.Value)
	return err
}

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, api, role) VALUES ($1, $2, $3)
`

type AssignRoleParams struct {
	UserID string
	Api    string
	Role   string
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.Api, arg.Role)
	return err
}

const closeSetup = `-- name: CloseSetup :exec
UPDATE settings SET setup_token = NULL, setup_done = true
`

func (q *Queries) CloseSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, closeSetup)
	return err
}

const createUser = `-- name: CreateUser :exec
WITH new_user AS (
    INSERT INTO users (id) VALUES ($1)
    RETURNING id
)
INSERT INTO user_roles (user_id, api, role)
SELECT u.id, r.api, r.key FROM new_user u JOIN roles r ON r.default_role
`

// The new User also picks up every default Role, in the same statement, so
// every creation path (code or password sign-up, Provider, bootstrap) agrees
// and the set is whatever the default Roles are at that moment.
func (q *Queries) CreateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}

const lockSetup = `-- name: LockSetup :one
SELECT setup_token, setup_done FROM settings FOR UPDATE
`

type LockSetupRow struct {
	SetupToken []byte
	SetupDone  bool
}

func (q *Queries) LockSetup(ctx context.Context) (LockSetupRow, error) {
	row := q.db.QueryRow(ctx, lockSetup)
	var i LockSetupRow
	err := row.Scan(&i.SetupToken, &i.SetupDone)
	return i, err
}

const needsConsent = `-- name: NeedsConsent :one
SELECT (s.terms_version <> '' AND NOT EXISTS (
    SELECT 1 FROM consents c WHERE c.user_id = $1 AND c.version = s.terms_version))::boolean
FROM settings s
`

// The instance has terms and the User has not agreed to this version.
func (q *Queries) NeedsConsent(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, needsConsent, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const needsPhone = `-- name: NeedsPhone :one
SELECT (s.require_phone AND NOT EXISTS (SELECT 1 FROM identifiers i WHERE i.user_id = $1 AND i.kind = 'phone'))::boolean
FROM settings s
`

// The instance requires a phone number and the User has none.
func (q *Queries) NeedsPhone(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, needsPhone, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const passwordByIdentifier = `-- name: PasswordByIdentifier :one
SELECT i.user_id, p.hash, (u.disabled_at IS NOT NULL)::boolean AS disabled,
       EXISTS (SELECT 1 FROM user_roles r
               WHERE r.user_id = i.user_id AND r.api = 'urn:stars-auth:management-api') AS admin
FROM identifiers i JOIN passwords p USING (user_id) JOIN users u ON u.id = i.user_id
WHERE i.value = $1
`

type PasswordByIdentifierRow struct {
	UserID   string
	Hash     string
	Disabled bool
	Admin    bool
}

func (q *Queries) PasswordByIdentifier(ctx context.Context, value string) (PasswordByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, passwordByIdentifier, value)
	var i PasswordByIdentifierRow
	err := row.Scan(
		&i.UserID,
		&i.Hash,
		&i.Disabled,
		&i.Admin,
	)
	return i, err
}

const passwordLogin = `-- name: PasswordLogin :one
SELECT password_login FROM settings
`

func (q *Queries) PasswordLogin(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, passwordLogin)
	var password_login string
	err := row.Scan(&password_login)
	return password_login, err
}

const recordConsent = `-- name: RecordConsent :exec
INSERT INTO consents (user_id, version, client_id) VALUES ($1, $2, $3)
`

type RecordConsentParams struct {
	UserID   string
	Version  string
	ClientID string
}

func (q *Queries) RecordConsent(ctx context.Context, arg RecordConsentParams) error {
	_, err := q.db.Exec(ctx, recordConsent, arg.UserID, arg.Version, arg.ClientID)
	return err
}

const setPassword = `-- name: SetPassword :exec
INSERT INTO passwords (user_id, hash) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET hash = EXCLUDED.hash
`

type SetPasswordParams struct {
	UserID string
	Hash   string
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.UserID, arg.Hash)
	return err
}

const setSetupToken = `-- name: SetSetupToken :exec
UPDATE settings SET setup_token = $1
`

func (q *Queries) SetSetupToken(ctx context.Context, setupToken []byte) error {
	_, err := q.db.Exec(ctx, setSetupToken, setupToken)
	return err
}

const terms = `-- name: Terms :one
SELECT terms_url, privacy_url, terms_version FROM settings
`

type TermsRow struct {
	TermsUrl     string
	PrivacyUrl   string
	TermsVersion string
}

func (q *Queries) Terms(ctx context.Context) (TermsRow, error) {
	row := q.db.QueryRow(ctx, terms)
	var i TermsRow
	err := row.Scan(&i.TermsUrl, &i.PrivacyUrl, &i.TermsVersion)
	return i, err
}

const userByIdentifier = `-- name: UserByIdentifier :one
SELECT i.user_id, (u.disabled_at IS NOT NULL)::boolean AS disabled
FROM identifiers i JOIN users u ON u.id = i.user_id WHERE i.value = $1
`

type UserByIdentifierRow struct {
	UserID   string
	Disabled bool
}

func (q *Queries) UserByIdentifier(ctx context.Context, value string) (UserByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, userByIdentifier, value)
	var i UserByIdentifierRow
	err := row.Scan(&i.UserID, &i.Disabled)
	return i, err
}

const userIdentifiers = `-- name: UserIdentifiers :many
SELECT kind, value FROM identifiers WHERE user_id = $1
`

type UserIdentifiersRow struct {
	Kind  string
	Value string
}

func (q *Queries) UserIdentifiers(ctx context.Context, userID string) ([]UserIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, userIdentifiers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentifiersRow
	for rows.Next() {
		var i UserIdentifiersRow
		if err := rows.Scan(&i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
