// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lockout.sql

package sqlc

import (
	"context"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
DELETE FROM login_failures WHERE key = $1
`

func (q *Queries) ClearLoginFailures(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, key)
	return err
}

const deleteOldLoginFailures = `-- name: DeleteOldLoginFailures :exec
WITH expired AS (DELETE FROM lockouts WHERE until < now())
DELETE FROM login_failures WHERE at < now() - interval '1 day'
`

func (q *Queries) DeleteOldLoginFailures(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldLoginFailures)
	return err
}

const lockOut = `-- name: LockOut :exec
WITH cleared AS (DELETE FROM login_failures WHERE login_failures.key = $1)
INSERT INTO lockouts (key, until) VALUES ($1, now() + make_interval(secs => $2::float8))
ON CONFLICT (key) DO UPDATE SET until = EXCLUDED.until
`

type LockOutParams struct {
	Key      string
	LockSecs float64
}

// Locks key out for a while; its count starts over.
func (q *Queries) LockOut(ctx context.Context, arg LockOutParams) error {
	_, err := q.db.Exec(ctx, lockOut, arg.Key, arg.LockSecs)
	return err
}

const lockedOut = `-- name: LockedOut :one
SELECT EXISTS (SELECT 1 FROM lockouts WHERE key = $1 AND until > now())
`

func (q *Queries) LockedOut(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, lockedOut, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loginFailed = `-- name: LoginFailed :one
WITH f AS (INSERT INTO login_failures (key) VALUES ($1))
SELECT (count(*) + 1)::int FROM login_failures
WHERE login_failures.key = $1 AND login_failures.at > now() - make_interval(secs => $2::float8)
`

type LoginFailedParams struct {
	Key        string
	WindowSecs float64
}

// Records a failure of key and returns its failures within the window,
// this one included.
func (q *Queries) LoginFailed(ctx context.Context, arg LoginFailedParams) (int32, error) {
	row := q.db.QueryRow(ctx, loginFailed, arg.Key, arg.WindowSecs)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
