// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const caller = `-- name: Caller :one
SELECT count(*) > 0 AS admin,
       COALESCE(array_agg(DISTINCT rp.permission ORDER BY rp.permission)
                FILTER (WHERE rp.permission IS NOT NULL), '{}')::text[] AS permissions
FROM user_roles ur LEFT JOIN role_permissions rp USING (api, role)
WHERE ur.user_id = $1 AND ur.api = $2
`

type CallerParams struct {
	UserID string
	Api    string
}

type CallerRow struct {
	Admin       bool
	Permissions []string
}

// Holding any Role on the API makes an admin, even one with no Permissions.
func (q *Queries) Caller(ctx context.Context, arg CallerParams) (CallerRow, error) {
	row := q.db.QueryRow(ctx, caller, arg.UserID, arg.Api)
	var i CallerRow
	err := row.Scan(&i.Admin, &i.Permissions)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT u.id, u.created_at,
       COALESCE((SELECT json_agg(json_build_object('kind', i.kind, 'value', i.value) ORDER BY i.kind)
                 FROM identifiers i WHERE i.user_id = u.id), '[]')::jsonb AS identifiers,
       COALESCE((SELECT json_agg(json_build_object('api', r.api, 'key', r.key, 'name', r.name) ORDER BY r.api, r.key)
                 FROM user_roles ur JOIN roles r ON r.api = ur.api AND r.key = ur.role
                 WHERE ur.user_id = u.id), '[]')::jsonb AS roles,
       EXISTS (SELECT 1 FROM passwords p WHERE p.user_id = u.id) AS has_password
FROM users u
WHERE u.id = $1
`

type GetUserRow struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	Identifiers []byte
	Roles       []byte
	HasPassword bool
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Identifiers,
		&i.Roles,
		&i.HasPassword,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT r.api, a.name AS api_name, r.key, r.name, r.builtin
FROM roles r JOIN apis a ON a.identifier = r.api
ORDER BY a.builtin DESC, r.api, r.builtin DESC, r.key
`

type ListRolesRow struct {
	Api     string
	ApiName string
	Key     string
	Name    string
	Builtin bool
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.Api,
			&i.ApiName,
			&i.Key,
			&i.Name,
			&i.Builtin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.created_at,
       COALESCE((SELECT json_agg(json_build_object('kind', i.kind, 'value', i.value) ORDER BY i.kind)
                 FROM identifiers i WHERE i.user_id = u.id), '[]')::jsonb AS identifiers,
       COALESCE((SELECT json_agg(json_build_object('api', r.api, 'key', r.key, 'name', r.name) ORDER BY r.api, r.key)
                 FROM user_roles ur JOIN roles r ON r.api = ur.api AND r.key = ur.role
                 WHERE ur.user_id = u.id), '[]')::jsonb AS roles
FROM users u
WHERE ($1::text = ''
       OR strpos(u.id, upper($1)) > 0
       OR EXISTS (SELECT 1 FROM identifiers i WHERE i.user_id = u.id AND strpos(i.value, lower($1)) > 0))
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.api = $3 AND ur.role = $2))
ORDER BY u.created_at DESC, u.id
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Search string
	Role   string
	Api    string
	Off    int32
	Lim    int32
}

type ListUsersRow struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	Identifiers []byte
	Roles       []byte
}

// Search matches part of the sub or of any Identifier. An empty role skips
// the Role filter.
// ponytail: strpos scans every row; add a pg_trgm index when the pool is big.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.Api,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Identifiers,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
