// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aPIBuiltin = `-- name: APIBuiltin :one
SELECT builtin FROM apis WHERE identifier = $1
`

func (q *Queries) APIBuiltin(ctx context.Context, identifier string) (bool, error) {
	row := q.db.QueryRow(ctx, aPIBuiltin, identifier)
	var builtin bool
	err := row.Scan(&builtin)
	return builtin, err
}

const caller = `-- name: Caller :one
SELECT count(*) > 0 AS admin,
       COALESCE(array_agg(DISTINCT rp.permission ORDER BY rp.permission)
                FILTER (WHERE rp.permission IS NOT NULL), '{}')::text[] AS permissions
FROM user_roles ur LEFT JOIN role_permissions rp USING (api, role)
WHERE ur.user_id = $1 AND ur.api = $2
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.id = ur.user_id AND u.disabled_at IS NOT NULL)
`

type CallerParams struct {
	UserID string
	Api    string
}

type CallerRow struct {
	Admin       bool
	Permissions []string
}

// Holding any Role on the API makes an admin, even one with no Permissions;
// a disabled User is none.
func (q *Queries) Caller(ctx context.Context, arg CallerParams) (CallerRow, error) {
	row := q.db.QueryRow(ctx, caller, arg.UserID, arg.Api)
	var i CallerRow
	err := row.Scan(&i.Admin, &i.Permissions)
	return i, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM user_roles ur JOIN users u ON u.id = ur.user_id
WHERE ur.api = 'urn:stars-auth:management-api' AND ur.role = 'owner' AND u.disabled_at IS NULL
`

// A disabled owner is no owner.
func (q *Queries) CountOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAPI = `-- name: DeleteAPI :execrows
DELETE FROM apis
WHERE apis.identifier = $1 AND NOT apis.builtin
  AND ($2::boolean OR NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.api = apis.identifier))
`

type DeleteAPIParams struct {
	Identifier string
	Force      bool
}

// Its Permissions, Roles and their assignments go with it, but only when
// force confirms that; no row while someone holds one of its Roles.
func (q *Queries) DeleteAPI(ctx context.Context, arg DeleteAPIParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPI, arg.Identifier, arg.Force)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE client_id = $1 AND NOT builtin
`

func (q *Queries) DeleteApplication(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, deleteApplication, clientID)
	return err
}

const deletePermission = `-- name: DeletePermission :execrows
DELETE FROM permissions WHERE api = $1 AND key = $2 AND NOT builtin
`

type DeletePermissionParams struct {
	Api string
	Key string
}

// Its Roles lose it too (role_permissions cascades).
func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermission, arg.Api, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles
WHERE roles.api = $1 AND roles.key = $2 AND NOT roles.builtin
  AND ($3::boolean OR NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.api = roles.api AND ur.role = roles.key))
`

type DeleteRoleParams struct {
	Api   string
	Key   string
	Force bool
}

// Its assignments go with it (user_roles cascades), but only when force
// confirms that; no row while someone holds it.
func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, arg.Api, arg.Key, arg.Force)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
WITH gone AS (
    DELETE FROM users WHERE users.id = $2 RETURNING users.id
), hooks AS (
    INSERT INTO webhook_deliveries (client_id, payload)
    SELECT a.client_id, jsonb_build_object(
        'type', 'user.deleted',
        'timestamp', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
        'data', jsonb_build_object('sub', gone.id))
    FROM gone, applications a WHERE a.webhook_url IS NOT NULL
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'user.deleted', gone.id, jsonb_build_object('by', $1::text) FROM gone
`

type DeleteUserParams struct {
	By     string
	UserID string
}

// Deletes a User with everything of theirs (foreign keys cascade); their
// audit events keep only the sub. Audited with who did it, and queues
// user.deleted for every Application with a webhook.
func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, arg.By, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSettings = `-- name: GetSettings :one
SELECT password_login, require_phone, daily_send_limit, terms_url, privacy_url, terms_version, audit_retention_days
FROM settings
`

type GetSettingsRow struct {
	PasswordLogin      string
	RequirePhone       bool
	DailySendLimit     int32
	TermsUrl           string
	PrivacyUrl         string
	TermsVersion       string
	AuditRetentionDays int32
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(
		&i.PasswordLogin,
		&i.RequirePhone,
		&i.DailySendLimit,
		&i.TermsUrl,
		&i.PrivacyUrl,
		&i.TermsVersion,
		&i.AuditRetentionDays,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT u.id, u.created_at, u.disabled_at,
       COALESCE((SELECT json_agg(json_build_object('kind', i.kind, 'value', i.value) ORDER BY i.kind)
                 FROM identifiers i WHERE i.user_id = u.id), '[]')::jsonb AS identifiers,
       COALESCE((SELECT json_agg(json_build_object('api', r.api, 'key', r.key, 'name', r.name) ORDER BY r.api, r.key)
                 FROM user_roles ur JOIN roles r ON r.api = ur.api AND r.key = ur.role
                 WHERE ur.user_id = u.id), '[]')::jsonb AS roles,
       EXISTS (SELECT 1 FROM passwords p WHERE p.user_id = u.id) AS has_password,
       EXISTS (SELECT 1 FROM totp_credentials t WHERE t.user_id = u.id AND t.confirmed_at IS NOT NULL) AS two_factor
FROM users u
WHERE u.id = $1
`

type GetUserRow struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	Identifiers []byte
	Roles       []byte
	HasPassword bool
	TwoFactor   bool
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.Identifiers,
		&i.Roles,
		&i.HasPassword,
		&i.TwoFactor,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :exec
INSERT INTO applications (client_id, name, type, secret_hash) VALUES ($1, '', $2, $3)
`

type InsertApplicationParams struct {
	ClientID   string
	Type       string
	SecretHash []byte
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) error {
	_, err := q.db.Exec(ctx, insertApplication, arg.ClientID, arg.Type, arg.SecretHash)
	return err
}

const listAPIs = `-- name: ListAPIs :many
SELECT a.identifier, a.name, a.builtin,
       COALESCE((SELECT json_agg(json_build_object('key', p.key, 'name', p.name, 'builtin', p.builtin) ORDER BY p.key)
                 FROM permissions p WHERE p.api = a.identifier), '[]')::jsonb AS permissions,
       COALESCE((SELECT json_agg(json_build_object(
                     'key', r.key, 'name', r.name, 'builtin', r.builtin,
                     'permissions', COALESCE((SELECT json_agg(rp.permission ORDER BY rp.permission) FROM role_permissions rp
                                              WHERE rp.api = r.api AND rp.role = r.key), '[]'),
                     'users', (SELECT count(*) FROM user_roles ur WHERE ur.api = r.api AND ur.role = r.key))
                     ORDER BY r.builtin DESC, r.key)
                 FROM roles r WHERE r.api = a.identifier), '[]')::jsonb AS roles
FROM apis a
ORDER BY a.builtin DESC, a.identifier
`

type ListAPIsRow struct {
	Identifier  string
	Name        string
	Builtin     bool
	Permissions []byte
	Roles       []byte
}

// Every API with its Permissions and Roles; users counts who holds a Role.
func (q *Queries) ListAPIs(ctx context.Context) ([]ListAPIsRow, error) {
	rows, err := q.db.Query(ctx, listAPIs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIsRow
	for rows.Next() {
		var i ListAPIsRow
		if err := rows.Scan(
			&i.Identifier,
			&i.Name,
			&i.Builtin,
			&i.Permissions,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT client_id, name, type, builtin, created_at, redirect_uris, post_logout_redirect_uris,
       COALESCE(default_api, '')::text AS default_api,
       COALESCE(extract(epoch FROM session_idle_timeout), 0)::int AS session_idle_timeout,
       refresh_tokens, COALESCE(webhook_url, '')::text AS webhook_url, webhook_secret_updated_at,
       apple_app_ids, android_apps
FROM applications
WHERE $1::text = '' OR client_id = $1
ORDER BY builtin DESC, created_at, client_id
`

type ListApplicationsRow struct {
	ClientID               string
	Name                   string
	Type                   string
	Builtin                bool
	CreatedAt              pgtype.Timestamptz
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultApi             string
	SessionIdleTimeout     int32
	RefreshTokens          bool
	WebhookUrl             string
	WebhookSecretUpdatedAt pgtype.Timestamptz
	AppleAppIds            []string
	AndroidApps            []byte
}

// One Application, or all of them for an empty client_id.
func (q *Queries) ListApplications(ctx context.Context, clientID string) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ClientID,
			&i.Name,
			&i.Type,
			&i.Builtin,
			&i.CreatedAt,
			&i.RedirectUris,
			&i.PostLogoutRedirectUris,
			&i.DefaultApi,
			&i.SessionIdleTimeout,
			&i.RefreshTokens,
			&i.WebhookUrl,
			&i.WebhookSecretUpdatedAt,
			&i.AppleAppIds,
			&i.AndroidApps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, event, COALESCE(sub, '')::text AS sub, detail,
       COALESCE((SELECT i.value FROM identifiers i WHERE i.user_id = audit_log.sub
                 ORDER BY array_position(ARRAY['phone', 'email', 'username'], i.kind) LIMIT 1), '')::text AS user_identifier,
       COALESCE((SELECT i.value FROM identifiers i WHERE i.user_id = audit_log.detail ->> 'by'
                 ORDER BY array_position(ARRAY['phone', 'email', 'username'], i.kind) LIMIT 1), '')::text AS by_identifier
FROM audit_log
WHERE ($1::text = '' OR event = $1)
  AND ($2::text = '' OR sub = $2 OR detail ->> 'by' = $2)
  AND ($3::timestamptz IS NULL OR at >= $3)
  AND ($4::timestamptz IS NULL OR at < $4)
  AND ($5::bigint = 0 OR id < $5)
ORDER BY id DESC
LIMIT $6
`

type ListAuditParams struct {
	Event  string
	Sub    string
	Since  pgtype.Timestamptz
	Until  pgtype.Timestamptz
	Before int64
	Lim    int32
}

type ListAuditRow struct {
	ID             int64
	At             pgtype.Timestamptz
	Event          string
	Sub            string
	Detail         []byte
	UserIdentifier string
	ByIdentifier   string
}

// Newest first. sub matches the User an event is about or the admin who
// did it; before pages by id; empty filters match all. user_identifier and
// by_identifier are their primary Identifiers (phone, email, username),
// empty once the User is gone.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.Event,
		arg.Sub,
		arg.Since,
		arg.Until,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Event,
			&i.Sub,
			&i.Detail,
			&i.UserIdentifier,
			&i.ByIdentifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT r.api, a.name AS api_name, r.key, r.name, r.builtin
FROM roles r JOIN apis a ON a.identifier = r.api
ORDER BY a.builtin DESC, r.api, r.builtin DESC, r.key
`

type ListRolesRow struct {
	Api     string
	ApiName string
	Key     string
	Name    string
	Builtin bool
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.Api,
			&i.ApiName,
			&i.Key,
			&i.Name,
			&i.Builtin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigningKeys = `-- name: ListSigningKeys :many
SELECT kid, created_at FROM signing_keys ORDER BY created_at DESC, kid
`

type ListSigningKeysRow struct {
	Kid       string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListSigningKeys(ctx context.Context) ([]ListSigningKeysRow, error) {
	rows, err := q.db.Query(ctx, listSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSigningKeysRow
	for rows.Next() {
		var i ListSigningKeysRow
		if err := rows.Scan(&i.Kid, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.created_at, u.disabled_at,
       COALESCE((SELECT json_agg(json_build_object('kind', i.kind, 'value', i.value) ORDER BY i.kind)
                 FROM identifiers i WHERE i.user_id = u.id), '[]')::jsonb AS identifiers,
       COALESCE((SELECT json_agg(json_build_object('api', r.api, 'key', r.key, 'name', r.name) ORDER BY r.api, r.key)
                 FROM user_roles ur JOIN roles r ON r.api = ur.api AND r.key = ur.role
                 WHERE ur.user_id = u.id), '[]')::jsonb AS roles
FROM users u
WHERE ($1::text = ''
       OR strpos(u.id, upper($1)) > 0
       OR EXISTS (SELECT 1 FROM identifiers i WHERE i.user_id = u.id AND strpos(i.value, lower($1)) > 0))
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.api = $3 AND ur.role = $2))
ORDER BY u.created_at DESC, u.id
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Search string
	Role   string
	Api    string
	Off    int32
	Lim    int32
}

type ListUsersRow struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
	Identifiers []byte
	Roles       []byte
}

// Search matches part of the sub or of any Identifier. An empty role skips
// the Role filter.
// ponytail: strpos scans every row; add a pg_trgm index when the pool is big.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.Api,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.Identifiers,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwners = `-- name: LockOwners :exec
SELECT pg_advisory_xact_lock(hashtext('owners'))
`

// Serialises changes that could leave the instance without an owner.
func (q *Queries) LockOwners(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOwners)
	return err
}

const overview = `-- name: Overview :one
SELECT (SELECT count(*) FROM users) AS users,
       (SELECT count(*) FROM sessions WHERE auth_time >= date_trunc('day', now())) AS logins_today,
       (SELECT count(*) FROM live_sessions) AS live_sessions,
       (SELECT count(*) FROM applications) AS applications,
       (SELECT count(*) FROM sends WHERE sent_at >= now() - interval '1 day') AS sends_last_day,
       (SELECT daily_send_limit FROM settings) AS daily_send_limit
`

type OverviewRow struct {
	Users          int64
	LoginsToday    int64
	LiveSessions   int64
	Applications   int64
	SendsLastDay   int64
	DailySendLimit int32
}

func (q *Queries) Overview(ctx context.Context) (OverviewRow, error) {
	row := q.db.QueryRow(ctx, overview)
	var i OverviewRow
	err := row.Scan(
		&i.Users,
		&i.LoginsToday,
		&i.LiveSessions,
		&i.Applications,
		&i.SendsLastDay,
		&i.DailySendLimit,
	)
	return i, err
}

const putAPI = `-- name: PutAPI :execrows
INSERT INTO apis (identifier, name) VALUES ($1, $2)
ON CONFLICT (identifier) DO UPDATE SET name = EXCLUDED.name WHERE NOT apis.builtin
`

type PutAPIParams struct {
	Identifier string
	Name       string
}

func (q *Queries) PutAPI(ctx context.Context, arg PutAPIParams) (int64, error) {
	result, err := q.db.Exec(ctx, putAPI, arg.Identifier, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putPermission = `-- name: PutPermission :exec
INSERT INTO permissions (api, key, name) VALUES ($1, $2, $3)
ON CONFLICT (api, key) DO UPDATE SET name = EXCLUDED.name
`

type PutPermissionParams struct {
	Api  string
	Key  string
	Name string
}

func (q *Queries) PutPermission(ctx context.Context, arg PutPermissionParams) error {
	_, err := q.db.Exec(ctx, putPermission, arg.Api, arg.Key, arg.Name)
	return err
}

const putRole = `-- name: PutRole :execrows
INSERT INTO roles (api, key, name) VALUES ($1, $2, $3)
ON CONFLICT (api, key) DO UPDATE SET name = EXCLUDED.name WHERE NOT roles.builtin
`

type PutRoleParams struct {
	Api  string
	Key  string
	Name string
}

func (q *Queries) PutRole(ctx context.Context, arg PutRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, putRole, arg.Api, arg.Key, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceIdentifier = `-- name: ReplaceIdentifier :execrows
WITH put AS (
    INSERT INTO identifiers (user_id, kind, value)
    SELECT users.id, $1, $3 FROM users WHERE users.id = $4
    ON CONFLICT (user_id, kind) DO UPDATE SET value = EXCLUDED.value
    RETURNING identifiers.user_id
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'identifier.replaced', put.user_id, jsonb_build_object('kind', $1::text, 'by', $2::text) FROM put
`

type ReplaceIdentifierParams struct {
	Kind   string
	By     string
	Value  string
	UserID string
}

// Sets a User's Identifier of a kind, replacing the one they had. Audited
// with who did it, without the values.
func (q *Queries) ReplaceIdentifier(ctx context.Context, arg ReplaceIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceIdentifier,
		arg.Kind,
		arg.By,
		arg.Value,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const roleUsers = `-- name: RoleUsers :one
SELECT r.builtin, (SELECT count(*) FROM user_roles ur WHERE ur.api = r.api AND ur.role = r.key) AS users
FROM roles r WHERE r.api = $1 AND r.key = $2
`

type RoleUsersParams struct {
	Api string
	Key string
}

type RoleUsersRow struct {
	Builtin bool
	Users   int64
}

func (q *Queries) RoleUsers(ctx context.Context, arg RoleUsersParams) (RoleUsersRow, error) {
	row := q.db.QueryRow(ctx, roleUsers, arg.Api, arg.Key)
	var i RoleUsersRow
	err := row.Scan(&i.Builtin, &i.Users)
	return i, err
}

const setApplicationSecret = `-- name: SetApplicationSecret :execrows
UPDATE applications SET secret_hash = $2 WHERE client_id = $1 AND type = 'confidential' AND NOT builtin
`

type SetApplicationSecretParams struct {
	ClientID   string
	SecretHash []byte
}

func (q *Queries) SetApplicationSecret(ctx context.Context, arg SetApplicationSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, setApplicationSecret, arg.ClientID, arg.SecretHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRolePermissions = `-- name: SetRolePermissions :exec
WITH gone AS (
    DELETE FROM role_permissions
    WHERE role_permissions.api = $1 AND role_permissions.role = $2 AND NOT (role_permissions.permission = ANY ($3::text[]))
)
INSERT INTO role_permissions (api, role, permission)
SELECT $1, $2, p FROM unnest($3::text[]) AS p
ON CONFLICT DO NOTHING
`

type SetRolePermissionsParams struct {
	Api         string
	Role        string
	Permissions []string
}

func (q *Queries) SetRolePermissions(ctx context.Context, arg SetRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, setRolePermissions, arg.Api, arg.Role, arg.Permissions)
	return err
}

const setUserDisabled = `-- name: SetUserDisabled :execrows
WITH changed AS (
    UPDATE users SET disabled_at = CASE WHEN $1::boolean THEN now() END
    WHERE users.id = $3 AND (users.disabled_at IS NOT NULL) <> $1::boolean
    RETURNING users.id
), ended AS (
    UPDATE sessions SET ended_at = now()
    WHERE sessions.user_id IN (SELECT changed.id FROM changed) AND $1::boolean AND sessions.ended_at IS NULL
)
INSERT INTO audit_log (event, sub, detail)
SELECT CASE WHEN $1::boolean THEN 'user.disabled' ELSE 'user.enabled' END AS event, changed.id, jsonb_build_object('by', $2::text)
FROM changed
`

type SetUserDisabledParams struct {
	Disabled bool
	By       string
	UserID   string
}

// Disables or restores a User; disabling ends all their Sessions. Audited
// with who did it; no row when nothing changed.
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserDisabled, arg.Disabled, arg.By, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserRoles = `-- name: SetUserRoles :exec
WITH gone AS (
    DELETE FROM user_roles
    WHERE user_roles.user_id = $1 AND user_roles.api = $2 AND NOT (user_roles.role = ANY ($3::text[]))
), added AS (
    INSERT INTO user_roles (user_id, api, role)
    SELECT $1, $2, r FROM unnest($3::text[]) AS r
    ON CONFLICT DO NOTHING
)
INSERT INTO audit_log (event, sub, detail)
VALUES ('roles.assigned', $1::text, jsonb_build_object('api', $2::text, 'roles', $3::text[], 'by', $4::text))
`

type SetUserRolesParams struct {
	UserID string
	Api    string
	Roles  []string
	By     string
}

// Makes roles a User's Roles on an API; audited with who did it.
func (q *Queries) SetUserRoles(ctx context.Context, arg SetUserRolesParams) error {
	_, err := q.db.Exec(ctx, setUserRoles,
		arg.UserID,
		arg.Api,
		arg.Roles,
		arg.By,
	)
	return err
}

const updateApplication = `-- name: UpdateApplication :execrows
UPDATE applications SET
    name = $1,
    redirect_uris = $2,
    post_logout_redirect_uris = $3,
    default_api = NULLIF($4::text, ''),
    session_idle_timeout = NULLIF($5::int, 0) * interval '1 second',
    refresh_tokens = $6,
    webhook_url = NULLIF($7::text, ''),
    webhook_secret = CASE WHEN $7 = '' THEN NULL ELSE COALESCE($8, webhook_secret) END,
    webhook_secret_updated_at = CASE WHEN $7 = '' THEN NULL
                                     WHEN $8 IS NOT NULL THEN now()
                                     ELSE webhook_secret_updated_at END,
    apple_app_ids = $9,
    android_apps = $10
WHERE client_id = $11 AND NOT builtin
`

type UpdateApplicationParams struct {
	Name                   string
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultApi             string
	IdleSecs               int32
	RefreshTokens          bool
	WebhookUrl             string
	WebhookSecret          []byte
	AppleAppIds            []string
	AndroidApps            []byte
	ClientID               string
}

// An empty webhook_url turns the webhook off; a NULL webhook_secret keeps
// the stored one. idle_secs 0 means the default Session lifetime.
func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateApplication,
		arg.Name,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.DefaultApi,
		arg.IdleSecs,
		arg.RefreshTokens,
		arg.WebhookUrl,
		arg.WebhookSecret,
		arg.AppleAppIds,
		arg.AndroidApps,
		arg.ClientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSettings = `-- name: UpdateSettings :exec
WITH u AS (
    UPDATE settings SET password_login = $2, require_phone = $3,
        daily_send_limit = $4, terms_url = $5, privacy_url = $6,
        terms_version = $7, audit_retention_days = $8
)
INSERT INTO audit_log (event, sub, detail)
VALUES ('settings.updated', NULL, jsonb_build_object('by', $1::text))
`

type UpdateSettingsParams struct {
	By                 string
	PasswordLogin      string
	RequirePhone       bool
	DailySendLimit     int32
	TermsUrl           string
	PrivacyUrl         string
	TermsVersion       string
	AuditRetentionDays int32
}

// Changes the login policy; audited with who did it.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSettings,
		arg.By,
		arg.PasswordLogin,
		arg.RequirePhone,
		arg.DailySendLimit,
		arg.TermsUrl,
		arg.PrivacyUrl,
		arg.TermsVersion,
		arg.AuditRetentionDays,
	)
	return err
}
