// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Api struct {
	Identifier string
	Name       string
	Builtin    bool
	CreatedAt  pgtype.Timestamptz
}

type Application struct {
	ClientID               string
	Name                   string
	Type                   string
	SecretHash             []byte
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultApi             pgtype.Text
	SessionIdleTimeout     pgtype.Interval
	Builtin                bool
	CreatedAt              pgtype.Timestamptz
}

type OidcAuthnSession struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type OidcGrant struct {
	ID               string
	AuthCodeHash     []byte
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	Sealed           []byte
}

type OidcLogoutSession struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type SigningKey struct {
	Kid       string
	CreatedAt pgtype.Timestamptz
	Sealed    []byte
}
