// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Api struct {
	Identifier string
	Name       string
	Builtin    bool
	CreatedAt  pgtype.Timestamptz
}

type Application struct {
	ClientID               string
	Name                   string
	Type                   string
	SecretHash             []byte
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultApi             pgtype.Text
	SessionIdleTimeout     pgtype.Interval
	Builtin                bool
	CreatedAt              pgtype.Timestamptz
	RefreshTokens          bool
}

type AuditLog struct {
	ID     int64
	At     pgtype.Timestamptz
	Event  string
	Sub    pgtype.Text
	Detail []byte
}

type Channel struct {
	Kind      string
	Plugin    string
	Config    []byte
	UpdatedAt pgtype.Timestamptz
}

type ChannelSecret struct {
	Kind      string
	Field     string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type Code struct {
	Identifier string
	Code       string
	Attempts   int32
	ExpiresAt  pgtype.Timestamptz
}

type Identifier struct {
	UserID string
	Kind   string
	Value  string
}

type LiveSession struct {
	ID string
}

type OidcAuthnSession struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type OidcGrant struct {
	ID               string
	AuthCodeHash     []byte
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	Sealed           []byte
	SessionID        pgtype.Text
}

type OidcLogoutSession struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type OidcSpentRefreshToken struct {
	Hash    []byte
	GrantID string
}

type Password struct {
	UserID string
	Hash   string
}

type Permission struct {
	Api     string
	Key     string
	Name    string
	Builtin bool
}

type PowSpent struct {
	Signature string
	ExpiresAt pgtype.Timestamptz
}

type Role struct {
	Api     string
	Key     string
	Name    string
	Builtin bool
}

type RolePermission struct {
	Api        string
	Role       string
	Permission string
}

type Send struct {
	Identifier string
	Ip         string
	SentAt     pgtype.Timestamptz
}

type Session struct {
	IDHash      []byte
	UserID      string
	AuthTime    pgtype.Timestamptz
	Amr         []string
	LastSeenAt  pgtype.Timestamptz
	ID          string
	ClientID    pgtype.Text
	IdleTimeout pgtype.Interval
	EndedAt     pgtype.Timestamptz
}

type Setting struct {
	ID             bool
	PasswordLogin  string
	SetupToken     []byte
	SetupDone      bool
	DailySendLimit int32
	RequirePhone   bool
	PowSecret      string
}

type SigningKey struct {
	Kid       string
	CreatedAt pgtype.Timestamptz
	Sealed    []byte
}

type User struct {
	ID        string
	CreatedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID string
	Api    string
	Role   string
}
