// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Api struct {
	Identifier string
	Name       string
	Builtin    bool
	CreatedAt  pgtype.Timestamptz
}

type Application struct {
	ClientID               string
	Name                   string
	Type                   string
	SecretHash             []byte
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultApi             pgtype.Text
	SessionIdleTimeout     pgtype.Interval
	Builtin                bool
	CreatedAt              pgtype.Timestamptz
	RefreshTokens          bool
	WebhookUrl             pgtype.Text
	WebhookSecret          []byte
	WebhookSecretUpdatedAt pgtype.Timestamptz
	AppleAppIds            []string
	AndroidApps            []byte
}

type AuditLog struct {
	ID     int64
	At     pgtype.Timestamptz
	Event  string
	Sub    pgtype.Text
	Detail []byte
}

type Channel struct {
	Kind      string
	Plugin    string
	Config    []byte
	UpdatedAt pgtype.Timestamptz
}

type ChannelSecret struct {
	Kind      string
	Field     string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type Code struct {
	Identifier string
	Code       string
	Attempts   int32
	ExpiresAt  pgtype.Timestamptz
}

type Consent struct {
	UserID   string
	Version  string
	ClientID string
	At       pgtype.Timestamptz
}

type ExternalIdentity struct {
	Provider  string
	Subject   string
	UserID    string
	Token     []byte
	CreatedAt pgtype.Timestamptz
}

type Identifier struct {
	UserID string
	Kind   string
	Value  string
}

type LiveSession struct {
	ID string
}

type Lockout struct {
	Key   string
	Until pgtype.Timestamptz
}

type LoginFailure struct {
	Key string
	At  pgtype.Timestamptz
}

type OidcAuthnSession struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type OidcChallengeSession struct {
	Hash      []byte
	ClientID  string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type OidcGrant struct {
	ID               string
	AuthCodeHash     []byte
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	Sealed           []byte
	SessionID        pgtype.Text
}

type OidcLogoutSession struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

type OidcSpentRefreshToken struct {
	Hash    []byte
	GrantID string
}

type Password struct {
	UserID string
	Hash   string
}

type Permission struct {
	Api     string
	Key     string
	Name    string
	Builtin bool
}

type PowSpent struct {
	Signature string
	ExpiresAt pgtype.Timestamptz
}

type Provider struct {
	ID        string
	Type      string
	Name      string
	Enabled   bool
	Config    []byte
	CreatedAt pgtype.Timestamptz
}

type ProviderLogin struct {
	StateHash    []byte
	Provider     string
	Nonce        string
	Verifier     string
	AuthnSession string
	ExpiresAt    pgtype.Timestamptz
	SessionID    pgtype.Text
	Reauth       bool
	CreatedAt    pgtype.Timestamptz
}

type ProviderSecret struct {
	Provider  string
	Field     string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type RecoveryCode struct {
	UserID string
	Mac    []byte
	UsedAt pgtype.Timestamptz
}

type Role struct {
	Api     string
	Key     string
	Name    string
	Builtin bool
}

type RolePermission struct {
	Api        string
	Role       string
	Permission string
}

type Send struct {
	Identifier string
	Ip         string
	SentAt     pgtype.Timestamptz
}

type Session struct {
	IDHash      []byte
	UserID      string
	AuthTime    pgtype.Timestamptz
	Amr         []string
	LastSeenAt  pgtype.Timestamptz
	ID          string
	ClientID    pgtype.Text
	IdleTimeout pgtype.Interval
	EndedAt     pgtype.Timestamptz
}

type Setting struct {
	ID                  bool
	PasswordLogin       string
	SetupToken          []byte
	SetupDone           bool
	DailySendLimit      int32
	RequirePhone        bool
	PowSecret           string
	TermsUrl            string
	PrivacyUrl          string
	TermsVersion        string
	AuditRetentionDays  int32
	AdminsNeedTwoFactor bool
}

type SigningKey struct {
	Kid       string
	CreatedAt pgtype.Timestamptz
	Sealed    []byte
}

type TotpCredential struct {
	UserID      string
	Secret      []byte
	ConfirmedAt pgtype.Timestamptz
	LastStep    int64
}

type User struct {
	ID         string
	CreatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}

type UserRole struct {
	UserID string
	Api    string
	Role   string
}

type WebhookDelivery struct {
	ID       string
	ClientID string
	Payload  []byte
	Attempts int32
	NextAt   pgtype.Timestamptz
}
