// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const application = `-- name: Application :one
SELECT client_id, name, type, secret_hash, redirect_uris, post_logout_redirect_uris, default_api, session_idle_timeout, builtin, created_at, refresh_tokens FROM applications WHERE client_id = $1
`

func (q *Queries) Application(ctx context.Context, clientID string) (Application, error) {
	row := q.db.QueryRow(ctx, application, clientID)
	var i Application
	err := row.Scan(
		&i.ClientID,
		&i.Name,
		&i.Type,
		&i.SecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.DefaultApi,
		&i.SessionIdleTimeout,
		&i.Builtin,
		&i.CreatedAt,
		&i.RefreshTokens,
	)
	return i, err
}

const authnSession = `-- name: AuthnSession :one
SELECT data FROM oidc_authn_sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) AuthnSession(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, authnSession, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const createApplication = `-- name: CreateApplication :exec
INSERT INTO applications (client_id, name, type, secret_hash, redirect_uris, post_logout_redirect_uris, default_api)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateApplicationParams struct {
	ClientID               string
	Name                   string
	Type                   string
	SecretHash             []byte
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultApi             pgtype.Text
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.Exec(ctx, createApplication,
		arg.ClientID,
		arg.Name,
		arg.Type,
		arg.SecretHash,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.DefaultApi,
	)
	return err
}

const deleteExpiredOIDC = `-- name: DeleteExpiredOIDC :exec
WITH g AS (DELETE FROM oidc_grants WHERE oidc_grants.expires_at < now()),
     a AS (DELETE FROM oidc_authn_sessions WHERE oidc_authn_sessions.expires_at < now())
DELETE FROM oidc_logout_sessions WHERE oidc_logout_sessions.expires_at < now()
`

func (q *Queries) DeleteExpiredOIDC(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOIDC)
	return err
}

const deleteRetiredSigningKeys = `-- name: DeleteRetiredSigningKeys :exec
DELETE FROM signing_keys WHERE kid NOT IN (
    SELECT kid FROM signing_keys ORDER BY created_at DESC, kid LIMIT 2
)
`

func (q *Queries) DeleteRetiredSigningKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRetiredSigningKeys)
	return err
}

const endReusedRefreshToken = `-- name: EndReusedRefreshToken :exec
WITH spent AS (
    SELECT g.id, g.session_id FROM oidc_spent_refresh_tokens s JOIN oidc_grants g ON g.id = s.grant_id
    WHERE s.hash = $1
), ended AS (
    UPDATE sessions SET ended_at = now()
    WHERE sessions.id IN (SELECT spent.session_id FROM spent) AND sessions.ended_at IS NULL
    RETURNING sessions.id, sessions.user_id
), dropped AS (
    DELETE FROM oidc_grants WHERE oidc_grants.id IN (SELECT spent.id FROM spent WHERE spent.session_id IS NULL)
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'refresh_token.reused', ended.user_id, jsonb_build_object('session', ended.id) FROM ended
`

// A spent refresh token came back: end its grant's Session (a grant outside
// any Session is deleted instead) and audit it.
func (q *Queries) EndReusedRefreshToken(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, endReusedRefreshToken, hash)
	return err
}

const grant = `-- name: Grant :one
SELECT id, auth_code_hash, refresh_token_hash, expires_at, sealed, session_id FROM oidc_grants
WHERE oidc_grants.id = $1 AND (expires_at IS NULL OR expires_at > now())
  AND (session_id IS NULL OR session_id IN (SELECT l.id FROM live_sessions l))
`

func (q *Queries) Grant(ctx context.Context, id string) (OidcGrant, error) {
	row := q.db.QueryRow(ctx, grant, id)
	var i OidcGrant
	err := row.Scan(
		&i.ID,
		&i.AuthCodeHash,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.Sealed,
		&i.SessionID,
	)
	return i, err
}

const grantByAuthCodeHash = `-- name: GrantByAuthCodeHash :one
SELECT id, auth_code_hash, refresh_token_hash, expires_at, sealed, session_id FROM oidc_grants
WHERE auth_code_hash = $1 AND (expires_at IS NULL OR expires_at > now())
  AND (session_id IS NULL OR session_id IN (SELECT l.id FROM live_sessions l))
`

func (q *Queries) GrantByAuthCodeHash(ctx context.Context, authCodeHash []byte) (OidcGrant, error) {
	row := q.db.QueryRow(ctx, grantByAuthCodeHash, authCodeHash)
	var i OidcGrant
	err := row.Scan(
		&i.ID,
		&i.AuthCodeHash,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.Sealed,
		&i.SessionID,
	)
	return i, err
}

const grantByRefreshTokenHash = `-- name: GrantByRefreshTokenHash :one
SELECT id, auth_code_hash, refresh_token_hash, expires_at, sealed, session_id FROM oidc_grants
WHERE refresh_token_hash = $1 AND (expires_at IS NULL OR expires_at > now())
  AND (session_id IS NULL OR session_id IN (SELECT l.id FROM live_sessions l))
`

func (q *Queries) GrantByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (OidcGrant, error) {
	row := q.db.QueryRow(ctx, grantByRefreshTokenHash, refreshTokenHash)
	var i OidcGrant
	err := row.Scan(
		&i.ID,
		&i.AuthCodeHash,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.Sealed,
		&i.SessionID,
	)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :exec
INSERT INTO signing_keys (kid, sealed) VALUES ($1, $2)
`

type InsertSigningKeyParams struct {
	Kid    string
	Sealed []byte
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) error {
	_, err := q.db.Exec(ctx, insertSigningKey, arg.Kid, arg.Sealed)
	return err
}

const lockSigningKeys = `-- name: LockSigningKeys :exec
SELECT pg_advisory_xact_lock(hashtext('signing_keys'))
`

func (q *Queries) LockSigningKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSigningKeys)
	return err
}

const logoutSession = `-- name: LogoutSession :one
SELECT data FROM oidc_logout_sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) LogoutSession(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, logoutSession, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :execrows
WITH g AS (
    UPDATE oidc_grants SET refresh_token_hash = $2, expires_at = $3, sealed = $4
    WHERE oidc_grants.id = $5 AND oidc_grants.refresh_token_hash = $1
    RETURNING oidc_grants.id, oidc_grants.session_id
), touched AS (
    UPDATE sessions SET last_seen_at = now() WHERE sessions.id = (SELECT g.session_id FROM g)
)
INSERT INTO oidc_spent_refresh_tokens (hash, grant_id) SELECT $1, g.id FROM g
`

type RotateRefreshTokenParams struct {
	OldHash   []byte
	NewHash   []byte
	ExpiresAt pgtype.Timestamptz
	Sealed    []byte
	ID        string
}

// Swaps the refresh token only if old_hash is still the current one, keeps
// the old one as spent, and counts the refresh as Session activity. No row:
// another request rotated it first.
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshToken,
		arg.OldHash,
		arg.NewHash,
		arg.ExpiresAt,
		arg.Sealed,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAuthnSession = `-- name: SaveAuthnSession :exec
INSERT INTO oidc_authn_sessions (id, expires_at, data) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET expires_at = EXCLUDED.expires_at, data = EXCLUDED.data
`

type SaveAuthnSessionParams struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

func (q *Queries) SaveAuthnSession(ctx context.Context, arg SaveAuthnSessionParams) error {
	_, err := q.db.Exec(ctx, saveAuthnSession, arg.ID, arg.ExpiresAt, arg.Data)
	return err
}

const saveGrant = `-- name: SaveGrant :exec
WITH g AS (
    INSERT INTO oidc_grants (id, auth_code_hash, refresh_token_hash, expires_at, session_id, sealed)
    VALUES ($2, $3, $4, $5, $6, $7)
    ON CONFLICT (id) DO UPDATE SET
        auth_code_hash = EXCLUDED.auth_code_hash,
        refresh_token_hash = EXCLUDED.refresh_token_hash,
        expires_at = EXCLUDED.expires_at,
        sealed = EXCLUDED.sealed
    RETURNING session_id
)
UPDATE sessions SET ended_at = now()
WHERE $1::boolean AND sessions.id_hash IS NULL AND sessions.ended_at IS NULL
  AND sessions.id = (SELECT g.session_id FROM g)
`

type SaveGrantParams struct {
	Revoked          bool
	ID               string
	AuthCodeHash     []byte
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	SessionID        pgtype.Text
	Sealed           []byte
}

// Revoking the refresh token of an App Session ends the Session: the chain
// is the Session.
func (q *Queries) SaveGrant(ctx context.Context, arg SaveGrantParams) error {
	_, err := q.db.Exec(ctx, saveGrant,
		arg.Revoked,
		arg.ID,
		arg.AuthCodeHash,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.SessionID,
		arg.Sealed,
	)
	return err
}

const saveLogoutSession = `-- name: SaveLogoutSession :exec
INSERT INTO oidc_logout_sessions (id, expires_at, data) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET expires_at = EXCLUDED.expires_at, data = EXCLUDED.data
`

type SaveLogoutSessionParams struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Data      []byte
}

func (q *Queries) SaveLogoutSession(ctx context.Context, arg SaveLogoutSessionParams) error {
	_, err := q.db.Exec(ctx, saveLogoutSession, arg.ID, arg.ExpiresAt, arg.Data)
	return err
}

const setRedirectURIs = `-- name: SetRedirectURIs :exec
UPDATE applications SET redirect_uris = $2, post_logout_redirect_uris = $3 WHERE client_id = $1
`

type SetRedirectURIsParams struct {
	ClientID               string
	RedirectUris           []string
	PostLogoutRedirectUris []string
}

func (q *Queries) SetRedirectURIs(ctx context.Context, arg SetRedirectURIsParams) error {
	_, err := q.db.Exec(ctx, setRedirectURIs, arg.ClientID, arg.RedirectUris, arg.PostLogoutRedirectUris)
	return err
}

const signingKeys = `-- name: SigningKeys :many
SELECT kid, sealed FROM signing_keys ORDER BY created_at DESC, kid LIMIT 2
`

type SigningKeysRow struct {
	Kid    string
	Sealed []byte
}

func (q *Queries) SigningKeys(ctx context.Context) ([]SigningKeysRow, error) {
	rows, err := q.db.Query(ctx, signingKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKeysRow
	for rows.Next() {
		var i SigningKeysRow
		if err := rows.Scan(&i.Kid, &i.Sealed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
