// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCode = `-- name: DeleteCode :execrows
DELETE FROM codes WHERE identifier = $1 AND code = $2
`

type DeleteCodeParams struct {
	Identifier string
	Code       string
}

func (q *Queries) DeleteCode(ctx context.Context, arg DeleteCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCode, arg.Identifier, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOTP = `-- name: DeleteExpiredOTP :exec
WITH c AS (DELETE FROM codes WHERE codes.expires_at < now())
DELETE FROM sends WHERE sends.sent_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredOTP(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTP)
	return err
}

const lockSends = `-- name: LockSends :exec
SELECT pg_advisory_xact_lock(hashtext('sends'))
`

// Serialises sends so two requests cannot both pass a limit.
// ponytail: one global lock; per-Identifier locks if sends get busy.
func (q *Queries) LockSends(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSends)
	return err
}

const putCode = `-- name: PutCode :exec
INSERT INTO codes (identifier, code, expires_at) VALUES ($1, $2, $3)
ON CONFLICT (identifier) DO UPDATE SET code = EXCLUDED.code, attempts = 0, expires_at = EXCLUDED.expires_at
`

type PutCodeParams struct {
	Identifier string
	Code       string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) PutCode(ctx context.Context, arg PutCodeParams) error {
	_, err := q.db.Exec(ctx, putCode, arg.Identifier, arg.Code, arg.ExpiresAt)
	return err
}

const recordSend = `-- name: RecordSend :exec
INSERT INTO sends (identifier, ip, sent_at) VALUES ($1, $2, $3)
`

type RecordSendParams struct {
	Identifier string
	Ip         string
	SentAt     pgtype.Timestamptz
}

func (q *Queries) RecordSend(ctx context.Context, arg RecordSendParams) error {
	_, err := q.db.Exec(ctx, recordSend, arg.Identifier, arg.Ip, arg.SentAt)
	return err
}

const sendCounts = `-- name: SendCounts :one
SELECT count(*) FILTER (WHERE identifier = $1 AND sent_at > $2) AS identifier_minute,
       count(*) FILTER (WHERE identifier = $1 AND sent_at > $3) AS identifier_hour,
       count(*) FILTER (WHERE identifier = $1) AS identifier_day,
       count(*) FILTER (WHERE ip = $4 AND sent_at > $3) AS ip_hour,
       count(*) AS instance_day,
       (SELECT daily_send_limit FROM settings) AS daily_limit
FROM sends
WHERE sent_at > $5
`

type SendCountsParams struct {
	Identifier string
	MinuteAgo  pgtype.Timestamptz
	HourAgo    pgtype.Timestamptz
	Ip         string
	DayAgo     pgtype.Timestamptz
}

type SendCountsRow struct {
	IdentifierMinute int64
	IdentifierHour   int64
	IdentifierDay    int64
	IpHour           int64
	InstanceDay      int64
	DailyLimit       int32
}

func (q *Queries) SendCounts(ctx context.Context, arg SendCountsParams) (SendCountsRow, error) {
	row := q.db.QueryRow(ctx, sendCounts,
		arg.Identifier,
		arg.MinuteAgo,
		arg.HourAgo,
		arg.Ip,
		arg.DayAgo,
	)
	var i SendCountsRow
	err := row.Scan(
		&i.IdentifierMinute,
		&i.IdentifierHour,
		&i.IdentifierDay,
		&i.IpHour,
		&i.InstanceDay,
		&i.DailyLimit,
	)
	return i, err
}

const tryCode = `-- name: TryCode :one
UPDATE codes SET attempts = attempts + 1
WHERE identifier = $1 AND attempts < 5 AND expires_at > $2
RETURNING code
`

type TryCodeParams struct {
	Identifier string
	Now        pgtype.Timestamptz
}

// Counts a try before the code is compared, so parallel guesses still get
// five in all.
func (q *Queries) TryCode(ctx context.Context, arg TryCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, tryCode, arg.Identifier, arg.Now)
	var code string
	err := row.Scan(&code)
	return code, err
}
