// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkey.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPasskey = `-- name: AddPasskey :one
WITH put AS (
    INSERT INTO passkeys (user_id, credential_id, public_key, sign_count, aaguid,
                          backup_eligible, backup_state, transports, name)
    VALUES ($1, $2, $3, $4, $5,
            $6, $7, $8, $9)
    ON CONFLICT DO NOTHING
    RETURNING id, name, created_at
), audit AS (
    INSERT INTO audit_log (event, sub, detail)
    SELECT 'passkey.added', $1::text, jsonb_build_object('by', $10::text, 'name', put.name) FROM put
)
SELECT id, name, created_at FROM put
`

type AddPasskeyParams struct {
	UserID         string
	CredentialID   []byte
	PublicKey      []byte
	SignCount      int64
	Aaguid         pgtype.UUID
	BackupEligible bool
	BackupState    bool
	Transports     []string
	Name           string
	By             string
}

type AddPasskeyRow struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

// Audited as passkey.added. No row when the credential already exists.
func (q *Queries) AddPasskey(ctx context.Context, arg AddPasskeyParams) (AddPasskeyRow, error) {
	row := q.db.QueryRow(ctx, addPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Aaguid,
		arg.BackupEligible,
		arg.BackupState,
		arg.Transports,
		arg.Name,
		arg.By,
	)
	var i AddPasskeyRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const auditPasskeyCounter = `-- name: AuditPasskeyCounter :exec
INSERT INTO audit_log (event, sub, detail)
VALUES ('passkey.counter_regressed', $1::text, jsonb_build_object('name', $2::text, 'count', $3::int8))
`

type AuditPasskeyCounterParams struct {
	Sub   string
	Name  string
	Count int64
}

// A login refused because the counter went backwards: the Passkey may have
// been cloned. Audited as passkey.counter_regressed.
func (q *Queries) AuditPasskeyCounter(ctx context.Context, arg AuditPasskeyCounterParams) error {
	_, err := q.db.Exec(ctx, auditPasskeyCounter, arg.Sub, arg.Name, arg.Count)
	return err
}

const deleteExpiredPasskeyChallenges = `-- name: DeleteExpiredPasskeyChallenges :exec
DELETE FROM passkey_challenges WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredPasskeyChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasskeyChallenges)
	return err
}

const deletePasskey = `-- name: DeletePasskey :execrows
WITH gone AS (
    DELETE FROM passkeys WHERE passkeys.id = $2 AND user_id = $3 RETURNING user_id, name
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'passkey.removed', gone.user_id, jsonb_build_object('by', $1::text, 'name', gone.name) FROM gone
`

type DeletePasskeyParams struct {
	By     string
	ID     string
	UserID string
}

// Audited as passkey.removed. No row when the Passkey is not the User's.
func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, arg.By, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const passkeyByCredentialID = `-- name: PasskeyByCredentialID :one
SELECT user_id, name, public_key, sign_count, backup_eligible, backup_state
FROM passkeys WHERE credential_id = $1
`

type PasskeyByCredentialIDRow struct {
	UserID         string
	Name           string
	PublicKey      []byte
	SignCount      int64
	BackupEligible bool
	BackupState    bool
}

// The Passkey a login assertion names: its owner and the key to check the
// signature with.
func (q *Queries) PasskeyByCredentialID(ctx context.Context, credentialID []byte) (PasskeyByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, passkeyByCredentialID, credentialID)
	var i PasskeyByCredentialIDRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
	)
	return i, err
}

const passkeyExclusions = `-- name: PasskeyExclusions :many
SELECT credential_id, transports FROM passkeys WHERE user_id = $1
`

type PasskeyExclusionsRow struct {
	CredentialID []byte
	Transports   []string
}

// The credential IDs a registration options must exclude: the User's
// Passkeys, so an authenticator holding one refuses to make another.
func (q *Queries) PasskeyExclusions(ctx context.Context, userID string) ([]PasskeyExclusionsRow, error) {
	rows, err := q.db.Query(ctx, passkeyExclusions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyExclusionsRow
	for rows.Next() {
		var i PasskeyExclusionsRow
		if err := rows.Scan(&i.CredentialID, &i.Transports); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const passkeyLogin = `-- name: PasskeyLogin :one
SELECT passkey_login FROM settings
`

// Whether the instance offers Passkey login (docs/spec/consoles.md#设置); a
// ceremony while it is off is refused.
func (q *Queries) PasskeyLogin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, passkeyLogin)
	var passkey_login bool
	err := row.Scan(&passkey_login)
	return passkey_login, err
}

const putPasskeyChallenge = `-- name: PutPasskeyChallenge :exec
INSERT INTO passkey_challenges (session_id, user_id, challenge, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id) DO UPDATE SET user_id = EXCLUDED.user_id,
    challenge = EXCLUDED.challenge, expires_at = EXCLUDED.expires_at
`

type PutPasskeyChallengeParams struct {
	SessionID string
	UserID    string
	Challenge string
	ExpiresAt pgtype.Timestamptz
}

// A registration challenge in flight for this Session, replacing one
// already there.
func (q *Queries) PutPasskeyChallenge(ctx context.Context, arg PutPasskeyChallengeParams) error {
	_, err := q.db.Exec(ctx, putPasskeyChallenge,
		arg.SessionID,
		arg.UserID,
		arg.Challenge,
		arg.ExpiresAt,
	)
	return err
}

const renamePasskey = `-- name: RenamePasskey :execrows
WITH renamed AS (
    UPDATE passkeys SET name = $2 WHERE passkeys.id = $3 AND user_id = $4 RETURNING user_id
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'passkey.renamed', renamed.user_id, jsonb_build_object('by', $1::text, 'name', $2::text) FROM renamed
`

type RenamePasskeyParams struct {
	By     string
	Name   string
	ID     string
	UserID string
}

// Audited as passkey.renamed. No row when the Passkey is not the User's.
func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, renamePasskey,
		arg.By,
		arg.Name,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const signInPasskey = `-- name: SignInPasskey :exec
UPDATE passkeys SET last_used_at = now(), sign_count = $2
WHERE credential_id = $1
`

type SignInPasskeyParams struct {
	CredentialID []byte
	SignCount    int64
}

func (q *Queries) SignInPasskey(ctx context.Context, arg SignInPasskeyParams) error {
	_, err := q.db.Exec(ctx, signInPasskey, arg.CredentialID, arg.SignCount)
	return err
}

const takePasskeyChallenge = `-- name: TakePasskeyChallenge :one
DELETE FROM passkey_challenges WHERE session_id = $1
RETURNING user_id, challenge, (expires_at > now()) AS live
`

type TakePasskeyChallengeRow struct {
	UserID    string
	Challenge string
	Live      bool
}

// Takes the Session's registration challenge, live or not; taken once.
func (q *Queries) TakePasskeyChallenge(ctx context.Context, sessionID string) (TakePasskeyChallengeRow, error) {
	row := q.db.QueryRow(ctx, takePasskeyChallenge, sessionID)
	var i TakePasskeyChallengeRow
	err := row.Scan(&i.UserID, &i.Challenge, &i.Live)
	return i, err
}

const userPasskeys = `-- name: UserPasskeys :many
SELECT id, name, created_at, last_used_at FROM passkeys
WHERE user_id = $1 ORDER BY created_at
`

type UserPasskeysRow struct {
	ID         string
	Name       string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) UserPasskeys(ctx context.Context, userID string) ([]UserPasskeysRow, error) {
	rows, err := q.db.Query(ctx, userPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPasskeysRow
	for rows.Next() {
		var i UserPasskeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
