// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pow.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredPoW = `-- name: DeleteExpiredPoW :exec
DELETE FROM pow_spent WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredPoW(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPoW)
	return err
}

const poWSecret = `-- name: PoWSecret :one
SELECT pow_secret FROM settings
`

func (q *Queries) PoWSecret(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, poWSecret)
	var pow_secret string
	err := row.Scan(&pow_secret)
	return pow_secret, err
}

const spendPoW = `-- name: SpendPoW :execrows
INSERT INTO pow_spent (signature, expires_at) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type SpendPoWParams struct {
	Signature string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SpendPoW(ctx context.Context, arg SpendPoWParams) (int64, error) {
	result, err := q.db.Exec(ctx, spendPoW, arg.Signature, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
