// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExternalIdentity = `-- name: AddExternalIdentity :exec
INSERT INTO external_identities (provider, subject, user_id, token) VALUES ($1, $2, $3, $4)
`

type AddExternalIdentityParams struct {
	Provider string
	Subject  string
	UserID   string
	Token    []byte
}

func (q *Queries) AddExternalIdentity(ctx context.Context, arg AddExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, addExternalIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Token,
	)
	return err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enabledProviders = `-- name: EnabledProviders :many
SELECT id, name FROM providers WHERE enabled ORDER BY created_at
`

type EnabledProvidersRow struct {
	ID   string
	Name string
}

func (q *Queries) EnabledProviders(ctx context.Context) ([]EnabledProvidersRow, error) {
	rows, err := q.db.Query(ctx, enabledProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnabledProvidersRow
	for rows.Next() {
		var i EnabledProvidersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvider = `-- name: GetProvider :one
SELECT type, name, enabled, config FROM providers WHERE id = $1
`

type GetProviderRow struct {
	Type    string
	Name    string
	Enabled bool
	Config  []byte
}

func (q *Queries) GetProvider(ctx context.Context, id string) (GetProviderRow, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i GetProviderRow
	err := row.Scan(
		&i.Type,
		&i.Name,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}

const getProviderForUpdate = `-- name: GetProviderForUpdate :one
SELECT type, config FROM providers WHERE id = $1 FOR UPDATE
`

type GetProviderForUpdateRow struct {
	Type   string
	Config []byte
}

func (q *Queries) GetProviderForUpdate(ctx context.Context, id string) (GetProviderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getProviderForUpdate, id)
	var i GetProviderForUpdateRow
	err := row.Scan(&i.Type, &i.Config)
	return i, err
}

const insertProvider = `-- name: InsertProvider :exec
INSERT INTO providers (id, type, name, config) VALUES ($1, $2, $3, $4)
`

type InsertProviderParams struct {
	ID     string
	Type   string
	Name   string
	Config []byte
}

func (q *Queries) InsertProvider(ctx context.Context, arg InsertProviderParams) error {
	_, err := q.db.Exec(ctx, insertProvider,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Config,
	)
	return err
}

const insertProviderLogin = `-- name: InsertProviderLogin :exec
INSERT INTO provider_logins (state_hash, provider, nonce, verifier, authn_session) VALUES ($1, $2, $3, $4, $5)
`

type InsertProviderLoginParams struct {
	StateHash    []byte
	Provider     string
	Nonce        string
	Verifier     string
	AuthnSession string
}

func (q *Queries) InsertProviderLogin(ctx context.Context, arg InsertProviderLoginParams) error {
	_, err := q.db.Exec(ctx, insertProviderLogin,
		arg.StateHash,
		arg.Provider,
		arg.Nonce,
		arg.Verifier,
		arg.AuthnSession,
	)
	return err
}

const listProviders = `-- name: ListProviders :many
SELECT p.id, p.type, p.name, p.enabled, p.config, p.created_at,
       COALESCE((SELECT jsonb_object_agg(s.field, s.updated_at) FROM provider_secrets s WHERE s.provider = p.id),
                '{}')::jsonb AS secrets,
       (SELECT count(*) FROM external_identities e WHERE e.provider = p.id) AS bound,
       (SELECT count(*) FROM external_identities e
        WHERE e.provider = p.id
          AND NOT EXISTS (SELECT 1 FROM external_identities o WHERE o.user_id = e.user_id AND o.provider <> p.id)
          AND NOT EXISTS (SELECT 1 FROM identifiers i WHERE i.user_id = e.user_id
                          AND (i.kind <> 'username' OR EXISTS (SELECT 1 FROM passwords pw WHERE pw.user_id = e.user_id)))
       ) AS only_login_path
FROM providers p
ORDER BY p.created_at
`

type ListProvidersRow struct {
	ID            string
	Type          string
	Name          string
	Enabled       bool
	Config        []byte
	CreatedAt     pgtype.Timestamptz
	Secrets       []byte
	Bound         int64
	OnlyLoginPath int64
}

// only_login_path counts the bound Users with no other way to sign in
// (docs/spec/identity.md#不变式).
func (q *Queries) ListProviders(ctx context.Context) ([]ListProvidersRow, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProvidersRow
	for rows.Next() {
		var i ListProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.CreatedAt,
			&i.Secrets,
			&i.Bound,
			&i.OnlyLoginPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerSecrets = `-- name: ProviderSecrets :many
SELECT field, value FROM provider_secrets WHERE provider = $1
`

type ProviderSecretsRow struct {
	Field string
	Value []byte
}

func (q *Queries) ProviderSecrets(ctx context.Context, provider string) ([]ProviderSecretsRow, error) {
	rows, err := q.db.Query(ctx, providerSecrets, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderSecretsRow
	for rows.Next() {
		var i ProviderSecretsRow
		if err := rows.Scan(&i.Field, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putProviderSecret = `-- name: PutProviderSecret :exec
INSERT INTO provider_secrets (provider, field, value) VALUES ($1, $2, $3)
ON CONFLICT (provider, field) DO UPDATE SET value = excluded.value, updated_at = now()
`

type PutProviderSecretParams struct {
	Provider string
	Field    string
	Value    []byte
}

func (q *Queries) PutProviderSecret(ctx context.Context, arg PutProviderSecretParams) error {
	_, err := q.db.Exec(ctx, putProviderSecret, arg.Provider, arg.Field, arg.Value)
	return err
}

const setProviderEnabled = `-- name: SetProviderEnabled :execrows
UPDATE providers SET enabled = $2 WHERE id = $1
`

type SetProviderEnabledParams struct {
	ID      string
	Enabled bool
}

func (q *Queries) SetProviderEnabled(ctx context.Context, arg SetProviderEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeProviderLogin = `-- name: TakeProviderLogin :one
DELETE FROM provider_logins WHERE state_hash = $1 AND provider = $2 AND expires_at > now()
RETURNING nonce, verifier, authn_session
`

type TakeProviderLoginParams struct {
	StateHash []byte
	Provider  string
}

type TakeProviderLoginRow struct {
	Nonce        string
	Verifier     string
	AuthnSession string
}

func (q *Queries) TakeProviderLogin(ctx context.Context, arg TakeProviderLoginParams) (TakeProviderLoginRow, error) {
	row := q.db.QueryRow(ctx, takeProviderLogin, arg.StateHash, arg.Provider)
	var i TakeProviderLoginRow
	err := row.Scan(&i.Nonce, &i.Verifier, &i.AuthnSession)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE providers SET name = $2, config = $3 WHERE id = $1
`

type UpdateProviderParams struct {
	ID     string
	Name   string
	Config []byte
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.Exec(ctx, updateProvider, arg.ID, arg.Name, arg.Config)
	return err
}

const userByExternalIdentity = `-- name: UserByExternalIdentity :one
SELECT e.user_id, (u.disabled_at IS NOT NULL)::boolean AS disabled
FROM external_identities e JOIN users u ON u.id = e.user_id
WHERE e.provider = $1 AND e.subject = $2
`

type UserByExternalIdentityParams struct {
	Provider string
	Subject  string
}

type UserByExternalIdentityRow struct {
	UserID   string
	Disabled bool
}

func (q *Queries) UserByExternalIdentity(ctx context.Context, arg UserByExternalIdentityParams) (UserByExternalIdentityRow, error) {
	row := q.db.QueryRow(ctx, userByExternalIdentity, arg.Provider, arg.Subject)
	var i UserByExternalIdentityRow
	err := row.Scan(&i.UserID, &i.Disabled)
	return i, err
}
