// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id_hash, client_id, user_id, auth_time, amr, idle_timeout)
SELECT $1, $2::text, u.id, $3, $4,
       COALESCE((SELECT session_idle_timeout FROM applications WHERE applications.client_id = $2),
                CASE WHEN $1::bytea IS NULL THEN interval '90 days' ELSE interval '30 days' END)
FROM users u WHERE u.id = $5 AND u.disabled_at IS NULL
RETURNING id, EXTRACT(EPOCH FROM idle_timeout)::integer AS idle_secs
`

type CreateSessionParams struct {
	IDHash   []byte
	ClientID string
	AuthTime pgtype.Timestamptz
	Amr      []string
	UserID   string
}

type CreateSessionRow struct {
	ID       string
	IdleSecs int32
}

// A NULL id_hash makes an App Session. The idle timeout is the
// Application's, or the default of the Session's kind. No row for a
// disabled User.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.IDHash,
		arg.ClientID,
		arg.AuthTime,
		arg.Amr,
		arg.UserID,
	)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.IdleSecs)
	return i, err
}

const deleteOldSessions = `-- name: DeleteOldSessions :exec
DELETE FROM sessions
WHERE ended_at < now() - interval '30 days'
   OR last_seen_at + idle_timeout < now() - interval '30 days'
`

// Ended or idle for more than 30 days (docs/spec/security-compliance.md).
func (q *Queries) DeleteOldSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldSessions)
	return err
}

const endBrowserSession = `-- name: EndBrowserSession :exec
UPDATE sessions SET ended_at = now() WHERE id_hash = $1 AND ended_at IS NULL
`

func (q *Queries) EndBrowserSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, endBrowserSession, idHash)
	return err
}

const endUserSession = `-- name: EndUserSession :execrows
WITH ended AS (
    UPDATE sessions SET ended_at = now()
    WHERE sessions.id = $2 AND sessions.user_id = $3 AND sessions.id IN (SELECT l.id FROM live_sessions l)
    RETURNING sessions.id, sessions.user_id
)
INSERT INTO audit_log (event, sub, detail)
SELECT 'session.ended', ended.user_id, jsonb_build_object('session', ended.id, 'by', $1::text) FROM ended
`

type EndUserSessionParams struct {
	By     string
	ID     string
	UserID string
}

// An admin signs a User out of one Session; audited with who did it.
func (q *Queries) EndUserSession(ctx context.Context, arg EndUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endUserSession, arg.By, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewSession = `-- name: RenewSession :one
UPDATE sessions SET id_hash = $1, auth_time = $2, amr = $3, last_seen_at = now()
WHERE sessions.id_hash = $4 AND sessions.user_id = $5
  AND sessions.id IN (SELECT l.id FROM live_sessions l)
RETURNING id, EXTRACT(EPOCH FROM idle_timeout)::integer AS idle_secs
`

type RenewSessionParams struct {
	NewHash  []byte
	AuthTime pgtype.Timestamptz
	Amr      []string
	OldHash  []byte
	UserID   string
}

type RenewSessionRow struct {
	ID       string
	IdleSecs int32
}

// The same User signed in again: new cookie, new auth_time, same Session.
func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) (RenewSessionRow, error) {
	row := q.db.QueryRow(ctx, renewSession,
		arg.NewHash,
		arg.AuthTime,
		arg.Amr,
		arg.OldHash,
		arg.UserID,
	)
	var i RenewSessionRow
	err := row.Scan(&i.ID, &i.IdleSecs)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions SET last_seen_at = now()
WHERE sessions.id_hash = $1 AND sessions.id IN (SELECT l.id FROM live_sessions l)
RETURNING id, user_id, auth_time, amr, EXTRACT(EPOCH FROM idle_timeout)::integer AS idle_secs
`

type TouchSessionRow struct {
	ID       string
	UserID   string
	AuthTime pgtype.Timestamptz
	Amr      []string
	IdleSecs int32
}

func (q *Queries) TouchSession(ctx context.Context, idHash []byte) (TouchSessionRow, error) {
	row := q.db.QueryRow(ctx, touchSession, idHash)
	var i TouchSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthTime,
		&i.Amr,
		&i.IdleSecs,
	)
	return i, err
}

const userSessions = `-- name: UserSessions :many
SELECT s.id, (s.id_hash IS NULL)::boolean AS app, s.client_id, COALESCE(a.name, s.client_id, '')::text AS application_name,
       s.auth_time, s.amr, s.last_seen_at,
       (s.last_seen_at + s.idle_timeout)::timestamptz AS expires_at, s.ended_at,
       (s.id IN (SELECT l.id FROM live_sessions l))::boolean AS active
FROM sessions s LEFT JOIN applications a USING (client_id) WHERE s.user_id = $1
ORDER BY s.last_seen_at DESC
`

type UserSessionsRow struct {
	ID              string
	App             bool
	ClientID        pgtype.Text
	ApplicationName string
	AuthTime        pgtype.Timestamptz
	Amr             []string
	LastSeenAt      pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	Active          bool
}

func (q *Queries) UserSessions(ctx context.Context, userID string) ([]UserSessionsRow, error) {
	rows, err := q.db.Query(ctx, userSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSessionsRow
	for rows.Next() {
		var i UserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.App,
			&i.ClientID,
			&i.ApplicationName,
			&i.AuthTime,
			&i.Amr,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
