// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: twofactor.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTOTPStep = `-- name: AcceptTOTPStep :execrows
UPDATE totp_credentials SET last_step = $1 WHERE user_id = $2 AND last_step < $1
`

type AcceptTOTPStepParams struct {
	Step   int64
	UserID string
}

// Accepts a code for step: once, and never after a later one.
func (q *Queries) AcceptTOTPStep(ctx context.Context, arg AcceptTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptTOTPStep, arg.Step, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addRecoveryCodes = `-- name: AddRecoveryCodes :exec
INSERT INTO recovery_codes (user_id, mac) SELECT $1, unnest($2::bytea[])
`

type AddRecoveryCodesParams struct {
	UserID string
	Macs   [][]byte
}

func (q *Queries) AddRecoveryCodes(ctx context.Context, arg AddRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, addRecoveryCodes, arg.UserID, arg.Macs)
	return err
}

const beginTOTP = `-- name: BeginTOTP :execrows
INSERT INTO totp_credentials (user_id, secret) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET secret = EXCLUDED.secret, last_step = 0
WHERE totp_credentials.confirmed_at IS NULL
`

type BeginTOTPParams struct {
	UserID string
	Secret []byte
}

// A new TOTP for the User to confirm, replacing one not yet confirmed; none
// while 两步验证 is on.
func (q *Queries) BeginTOTP(ctx context.Context, arg BeginTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginTOTP, arg.UserID, arg.Secret)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmTOTP = `-- name: ConfirmTOTP :exec
UPDATE totp_credentials SET confirmed_at = now(), last_step = $1 WHERE user_id = $2
`

type ConfirmTOTPParams struct {
	Step   int64
	UserID string
}

// Turns 两步验证 on with the step of the code that confirmed it.
func (q *Queries) ConfirmTOTP(ctx context.Context, arg ConfirmTOTPParams) error {
	_, err := q.db.Exec(ctx, confirmTOTP, arg.Step, arg.UserID)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteTOTP = `-- name: DeleteTOTP :exec
DELETE FROM totp_credentials WHERE user_id = $1
`

func (q *Queries) DeleteTOTP(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteTOTP, userID)
	return err
}

const lockTOTP = `-- name: LockTOTP :one
SELECT secret, confirmed_at, last_step FROM totp_credentials WHERE user_id = $1 FOR UPDATE
`

type LockTOTPRow struct {
	Secret      []byte
	ConfirmedAt pgtype.Timestamptz
	LastStep    int64
}

// Serialises changes to a User's 两步验证.
func (q *Queries) LockTOTP(ctx context.Context, userID string) (LockTOTPRow, error) {
	row := q.db.QueryRow(ctx, lockTOTP, userID)
	var i LockTOTPRow
	err := row.Scan(&i.Secret, &i.ConfirmedAt, &i.LastStep)
	return i, err
}

const tOTP = `-- name: TOTP :one
SELECT secret, confirmed_at, last_step FROM totp_credentials WHERE user_id = $1
`

type TOTPRow struct {
	Secret      []byte
	ConfirmedAt pgtype.Timestamptz
	LastStep    int64
}

func (q *Queries) TOTP(ctx context.Context, userID string) (TOTPRow, error) {
	row := q.db.QueryRow(ctx, tOTP, userID)
	var i TOTPRow
	err := row.Scan(&i.Secret, &i.ConfirmedAt, &i.LastStep)
	return i, err
}

const unusedRecoveryCodes = `-- name: UnusedRecoveryCodes :many
SELECT c.mac FROM recovery_codes c
JOIN totp_credentials t ON t.user_id = c.user_id AND t.confirmed_at IS NOT NULL
WHERE c.user_id = $1 AND c.used_at IS NULL
`

// The User's recovery codes not yet used, while 两步验证 is on.
func (q *Queries) UnusedRecoveryCodes(ctx context.Context, userID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, unusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var mac []byte
		if err := rows.Scan(&mac); err != nil {
			return nil, err
		}
		items = append(items, mac)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
WITH used AS (
    UPDATE recovery_codes SET used_at = now() WHERE user_id = $1 AND mac = $2 AND used_at IS NULL
    RETURNING user_id
)
INSERT INTO audit_log (event, sub, detail) SELECT 'recovery_code.used', used.user_id, '{}'::jsonb FROM used
`

type UseRecoveryCodeParams struct {
	UserID string
	Mac    []byte
}

// Uses up a recovery code. Audited.
func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.Mac)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
