// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package sqlc

import (
	"context"
)

const claimDeliveries = `-- name: ClaimDeliveries :many
UPDATE webhook_deliveries AS d SET next_at = now() + interval '5 minutes', attempts = d.attempts + 1
FROM applications a
WHERE a.client_id = d.client_id
  AND d.id IN (SELECT w.id FROM webhook_deliveries w WHERE w.next_at <= now() ORDER BY w.next_at LIMIT 20 FOR UPDATE SKIP LOCKED)
RETURNING d.id, d.client_id, d.payload, d.attempts, COALESCE(a.webhook_url, '')::text AS url, a.webhook_secret AS secret
`

type ClaimDeliveriesRow struct {
	ID       string
	ClientID string
	Payload  []byte
	Attempts int32
	Url      string
	Secret   []byte
}

// Due deliveries, each held back for 5 minutes while it is being sent so
// that no other replica sends it too.
func (q *Queries) ClaimDeliveries(ctx context.Context) ([]ClaimDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDeliveriesRow
	for rows.Next() {
		var i ClaimDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Payload,
			&i.Attempts,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDelivery = `-- name: DeleteDelivery :exec
DELETE FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) DeleteDelivery(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDelivery, id)
	return err
}

const retryDelivery = `-- name: RetryDelivery :exec
UPDATE webhook_deliveries SET next_at = now() + make_interval(secs => $1::integer) WHERE id = $2
`

type RetryDeliveryParams struct {
	WaitSecs int32
	ID       string
}

func (q *Queries) RetryDelivery(ctx context.Context, arg RetryDeliveryParams) error {
	_, err := q.db.Exec(ctx, retryDelivery, arg.WaitSecs, arg.ID)
	return err
}
