#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Usage: deploy/deploy.sh      first deploy or interactive update
#        deploy/deploy.sh -y   update without prompts (after the first deploy)

TOTAL_STAGES=5

cd "$(dirname "$0")/.." # repo root: the build context
HOST="${DEPLOY_HOST:-root@192.168.50.50}"
DIR=/opt/auth
REGISTRY=registry.starsdom.com:9443
IMAGE=$REGISTRY/zibyn/stars-auth:latest
ENV_FILE=/dev/null # nothing is kept locally; every secret lives in $DIR/.env
AUTO=""; [[ "${1:-}" == -y ]] && AUTO=1

[[ $AUTO ]] || banner "部署 Stars Auth 到 $HOST:$DIR"

stage "检查本机与服务器"
for c in docker ssh scp; do
  command -v "$c" >/dev/null || { warn "本机缺少 $c"; exit 1; }
done
ssh -o BatchMode=yes -o ConnectTimeout=5 "$HOST" true ||
  { warn "无法免密 SSH 到 $HOST。先执行: ssh-copy-id $HOST"; exit 1; }
ssh "$HOST" docker compose version >/dev/null ||
  { warn "$HOST 上没有 docker compose 插件"; exit 1; }
case "$(ssh "$HOST" uname -m)" in
  x86_64) ARCH=amd64 ;;
  aarch64 | arm64) ARCH=arm64 ;;
  *) warn "不支持的服务器架构: $(ssh "$HOST" uname -m)"; exit 1 ;;
esac
say "✓ $HOST 可以连接,架构 linux/$ARCH"

stage "登录镜像仓库 $REGISTRY"
note "保存过凭据就直接通过,否则输入仓库的用户名和密码。"
step "本机"
docker login "$REGISTRY"
step "$HOST"
ssh -t "$HOST" docker login "$REGISTRY"

stage "初始化 $DIR/.env"
if ssh "$HOST" test -f "$DIR/.env"; then
  say "✓ $DIR/.env 已存在,保持不变。要改域名、代理 IP 或端口,直接在服务器上编辑它。"
elif [[ $AUTO ]]; then
  warn "首次部署需要回答几个问题:去掉 -y 再运行一次。"; exit 1
else
  DOMAIN=""
  while [[ -z $DOMAIN ]]; do ask DOMAIN "Stars Auth 的域名(如 auth.example.com):"; done
  ask PROXY_IP "反向代理的 IP(代理就在 $HOST 上则直接回车):"
  ask PORT "暴露给反向代理的端口(回车用 8080):"
  warn "域名上线后不要再改:改了以后已签发的令牌和 Application 配置都会失效。"
  # The secrets are generated on the server and never touch this machine.
  ssh "$HOST" "umask 077 && mkdir -p $DIR && cat > $DIR/.env" <<END
STARS_AUTH_ISSUER=https://$DOMAIN
STARS_AUTH_PORT=${PORT:-8080}
PROXY_IP=$PROXY_IP
END
  ssh "$HOST" "umask 077 && cd $DIR && printf 'STARS_AUTH_MASTER_KEY=%s\nPOSTGRES_PASSWORD=%s\n' \"\$(head -c 32 /dev/urandom | base64)\" \"\$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')\" >> .env"
  say "✓ 已写入 $HOST:$DIR/.env"
  printf '\n'
  warn "备份主密钥!丢了它,签名私钥、TOTP 密钥、Channel 与 Provider 的密钥都无法还原:"
  ssh "$HOST" "grep ^STARS_AUTH_MASTER_KEY= $DIR/.env"
  until confirm "已经把它存进密码管理器或离线介质了吗?"; do :; done
fi

stage "构建并推送 $IMAGE"
[[ $AUTO ]] || pause "按回车开始构建 linux/$ARCH 镜像"
docker buildx build --platform "linux/$ARCH" -t "$IMAGE" --push .

stage "部署到 $HOST:$DIR"
scp -q deploy/docker-compose.yaml "$HOST:$DIR/docker-compose.yaml"
# No rolling upgrade: `up` stops the old container before the new one starts
# and migrates. Back up first, since downgrades are not supported.
ssh "$HOST" "cd $DIR && sh -es" <<'END'
if [ -n "$(docker compose ps -q postgres)" ]; then
  mkdir -p backups
  f=backups/stars-$(date +%Y%m%d-%H%M%S).dump
  docker compose exec -T postgres pg_dump -U stars -Fc stars > "$f"
  echo "  ✓ 已备份数据库 → /opt/auth/$f"
  ls -t backups/*.dump | tail -n +11 | xargs -r rm -- # keep the newest 10
fi
docker compose pull -q
docker compose up -d --wait --wait-timeout 120
docker image prune -f >/dev/null
END
SETUP=$(ssh "$HOST" "cd $DIR && docker compose logs stars-auth" | grep -o 'https://[^" ]*/setup?token=[^" ]*' | tail -n1 || true)

finish
say "✓ $IMAGE 已在 $HOST:$DIR 运行"
[[ -n $SETUP ]] && say "首次引导:打开 $SETUP"
say "以后更新:deploy/deploy.sh -y"
printf '\n'
