-- +goose Up

-- An API is identified by the string access tokens carry as aud.
CREATE TABLE apis (
    identifier text PRIMARY KEY,
    name       text NOT NULL,
    builtin    boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE applications (
    client_id                 text PRIMARY KEY,
    name                      text NOT NULL,
    type                      text NOT NULL CHECK (type IN ('public', 'confidential')),
    -- SHA-256 of the client secret (high-entropy, generated by us).
    secret_hash               bytea,
    redirect_uris             text[] NOT NULL DEFAULT '{}',
    post_logout_redirect_uris text[] NOT NULL DEFAULT '{}',
    default_api               text REFERENCES apis (identifier),
    -- Idle Session lifetime; NULL means the default (docs/spec/protocol.md#session).
    session_idle_timeout      interval,
    builtin                   boolean NOT NULL DEFAULT false,
    created_at                timestamptz NOT NULL DEFAULT now(),
    CHECK ((type = 'confidential') = (secret_hash IS NOT NULL))
);

INSERT INTO apis (identifier, name, builtin)
VALUES ('urn:stars-auth:management-api', 'Management API', true);

-- Redirect URIs depend on the issuer; the console wires them up when it lands.
INSERT INTO applications (client_id, name, type, default_api, builtin)
VALUES ('stars-auth-console', 'Stars Auth 管理端', 'public', 'urn:stars-auth:management-api', true);

-- go-oidc records. Short-lived rows carry expires_at and are deleted by the
-- hourly cleanup. Grants hold bearer secrets (auth code, refresh token), so the
-- whole record is sealed with the master key and looked up by SHA-256.
CREATE TABLE oidc_grants (
    id                 text PRIMARY KEY,
    auth_code_hash     bytea UNIQUE,
    refresh_token_hash bytea UNIQUE,
    -- NULL: a refresh token without expiry keeps the grant alive.
    expires_at         timestamptz,
    sealed             bytea NOT NULL
);
CREATE INDEX ON oidc_grants (expires_at);

CREATE TABLE oidc_authn_sessions (
    id         text PRIMARY KEY,
    expires_at timestamptz NOT NULL,
    data       jsonb NOT NULL
);
CREATE INDEX ON oidc_authn_sessions (expires_at);

CREATE TABLE oidc_logout_sessions (
    id         text PRIMARY KEY,
    expires_at timestamptz NOT NULL,
    data       jsonb NOT NULL
);
CREATE INDEX ON oidc_logout_sessions (expires_at);

-- RS256 signing keys, PKCS #8 sealed with the master key. The newest signs;
-- the one before it stays in the JWKS so tokens it signed still verify.
CREATE TABLE signing_keys (
    kid        text PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    sealed     bytea NOT NULL
);
