/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AccountCallbackRouteImport } from './routes/account_.callback'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleAuditRouteImport } from './routes/console.audit'
import { Route as ConsoleSettingsRouteImport } from './routes/console.settings'
import { Route as ConsoleCallbackRouteImport } from './routes/console_.callback'
import { Route as ConsoleApisIndexRouteImport } from './routes/console.apis.index'
import { Route as ConsoleApisApiRouteImport } from './routes/console.apis.$api'
import { Route as ConsoleAppsIndexRouteImport } from './routes/console.apps.index'
import { Route as ConsoleAppsClientIdRouteImport } from './routes/console.apps.$clientId'
import { Route as ConsoleAppsNewRouteImport } from './routes/console.apps.new'
import { Route as ConsoleUsersIndexRouteImport } from './routes/console.users.index'
import { Route as ConsoleUsersSubRouteImport } from './routes/console.users.$sub'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCallbackRoute = AccountCallbackRouteImport.update({
  id: '/account_/callback',
  path: '/account/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCallbackRoute = ConsoleCallbackRouteImport.update({
  id: '/console_/callback',
  path: '/console/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleApisIndexRoute = ConsoleApisIndexRouteImport.update({
  id: '/apis/',
  path: '/apis/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleApisApiRoute = ConsoleApisApiRouteImport.update({
  id: '/apis/$api',
  path: '/apis/$api',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsIndexRoute = ConsoleAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsClientIdRoute = ConsoleAppsClientIdRouteImport.update({
  id: '/apps/$clientId',
  path: '/apps/$clientId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsNewRoute = ConsoleAppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersIndexRoute = ConsoleUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersSubRoute = ConsoleUsersSubRouteImport.update({
  id: '/users/$sub',
  path: '/users/$sub',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/console': typeof ConsoleRouteWithChildren
  '/account/callback': typeof AccountCallbackRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/callback': typeof ConsoleCallbackRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/apis/$api': typeof ConsoleApisApiRoute
  '/console/apps/$clientId': typeof ConsoleAppsClientIdRoute
  '/console/apps/new': typeof ConsoleAppsNewRoute
  '/console/users/$sub': typeof ConsoleUsersSubRoute
  '/console/apis/': typeof ConsoleApisIndexRoute
  '/console/apps/': typeof ConsoleAppsIndexRoute
  '/console/users/': typeof ConsoleUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/account/callback': typeof AccountCallbackRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/callback': typeof ConsoleCallbackRoute
  '/console': typeof ConsoleIndexRoute
  '/console/apis/$api': typeof ConsoleApisApiRoute
  '/console/apps/$clientId': typeof ConsoleAppsClientIdRoute
  '/console/apps/new': typeof ConsoleAppsNewRoute
  '/console/users/$sub': typeof ConsoleUsersSubRoute
  '/console/apis': typeof ConsoleApisIndexRoute
  '/console/apps': typeof ConsoleAppsIndexRoute
  '/console/users': typeof ConsoleUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/console': typeof ConsoleRouteWithChildren
  '/account_/callback': typeof AccountCallbackRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console_/callback': typeof ConsoleCallbackRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/apis/$api': typeof ConsoleApisApiRoute
  '/console/apps/$clientId': typeof ConsoleAppsClientIdRoute
  '/console/apps/new': typeof ConsoleAppsNewRoute
  '/console/users/$sub': typeof ConsoleUsersSubRoute
  '/console/apis/': typeof ConsoleApisIndexRoute
  '/console/apps/': typeof ConsoleAppsIndexRoute
  '/console/users/': typeof ConsoleUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/account'
    | '/console'
    | '/account/callback'
    | '/console/audit'
    | '/console/settings'
    | '/console/callback'
    | '/console/'
    | '/console/apis/$api'
    | '/console/apps/$clientId'
    | '/console/apps/new'
    | '/console/users/$sub'
    | '/console/apis/'
    | '/console/apps/'
    | '/console/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/account'
    | '/account/callback'
    | '/console/audit'
    | '/console/settings'
    | '/console/callback'
    | '/console'
    | '/console/apis/$api'
    | '/console/apps/$clientId'
    | '/console/apps/new'
    | '/console/users/$sub'
    | '/console/apis'
    | '/console/apps'
    | '/console/users'
  id:
    | '__root__'
    | '/$'
    | '/account'
    | '/console'
    | '/account_/callback'
    | '/console/audit'
    | '/console/settings'
    | '/console_/callback'
    | '/console/'
    | '/console/apis/$api'
    | '/console/apps/$clientId'
    | '/console/apps/new'
    | '/console/users/$sub'
    | '/console/apis/'
    | '/console/apps/'
    | '/console/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  AccountCallbackRoute: typeof AccountCallbackRoute
  ConsoleCallbackRoute: typeof ConsoleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/callback': {
      id: '/account_/callback'
      path: '/account/callback'
      fullPath: '/account/callback'
      preLoaderRoute: typeof AccountCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/audit': {
      id: '/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console_/callback': {
      id: '/console_/callback'
      path: '/console/callback'
      fullPath: '/console/callback'
      preLoaderRoute: typeof ConsoleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/apis/': {
      id: '/console/apis/'
      path: '/apis'
      fullPath: '/console/apis/'
      preLoaderRoute: typeof ConsoleApisIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apis/$api': {
      id: '/console/apis/$api'
      path: '/apis/$api'
      fullPath: '/console/apis/$api'
      preLoaderRoute: typeof ConsoleApisApiRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apps/': {
      id: '/console/apps/'
      path: '/apps'
      fullPath: '/console/apps/'
      preLoaderRoute: typeof ConsoleAppsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apps/$clientId': {
      id: '/console/apps/$clientId'
      path: '/apps/$clientId'
      fullPath: '/console/apps/$clientId'
      preLoaderRoute: typeof ConsoleAppsClientIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apps/new': {
      id: '/console/apps/new'
      path: '/apps/new'
      fullPath: '/console/apps/new'
      preLoaderRoute: typeof ConsoleAppsNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/users/': {
      id: '/console/users/'
      path: '/users'
      fullPath: '/console/users/'
      preLoaderRoute: typeof ConsoleUsersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/users/$sub': {
      id: '/console/users/$sub'
      path: '/users/$sub'
      fullPath: '/console/users/$sub'
      preLoaderRoute: typeof ConsoleUsersSubRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleApisApiRoute: typeof ConsoleApisApiRoute
  ConsoleAppsClientIdRoute: typeof ConsoleAppsClientIdRoute
  ConsoleAppsNewRoute: typeof ConsoleAppsNewRoute
  ConsoleUsersSubRoute: typeof ConsoleUsersSubRoute
  ConsoleApisIndexRoute: typeof ConsoleApisIndexRoute
  ConsoleAppsIndexRoute: typeof ConsoleAppsIndexRoute
  ConsoleUsersIndexRoute: typeof ConsoleUsersIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleApisApiRoute: ConsoleApisApiRoute,
  ConsoleAppsClientIdRoute: ConsoleAppsClientIdRoute,
  ConsoleAppsNewRoute: ConsoleAppsNewRoute,
  ConsoleUsersSubRoute: ConsoleUsersSubRoute,
  ConsoleApisIndexRoute: ConsoleApisIndexRoute,
  ConsoleAppsIndexRoute: ConsoleAppsIndexRoute,
  ConsoleUsersIndexRoute: ConsoleUsersIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  AccountCallbackRoute: AccountCallbackRoute,
  ConsoleCallbackRoute: ConsoleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
