/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AccountCallbackRouteImport } from './routes/account_.callback'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleApisRouteImport } from './routes/console.apis'
import { Route as ConsoleAppsRouteImport } from './routes/console.apps'
import { Route as ConsoleAuditRouteImport } from './routes/console.audit'
import { Route as ConsoleLoginRouteImport } from './routes/console.login'
import { Route as ConsoleSettingsRouteImport } from './routes/console.settings'
import { Route as ConsoleCallbackRouteImport } from './routes/console_.callback'
import { Route as ConsoleLoginIndexRouteImport } from './routes/console.login.index'
import { Route as ConsoleLoginChannelsRouteImport } from './routes/console.login.channels'
import { Route as ConsoleUsersIndexRouteImport } from './routes/console.users.index'
import { Route as ConsoleUsersSubRouteImport } from './routes/console.users.$sub'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCallbackRoute = AccountCallbackRouteImport.update({
  id: '/account_/callback',
  path: '/account/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleApisRoute = ConsoleApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsRoute = ConsoleAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLoginRoute = ConsoleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCallbackRoute = ConsoleCallbackRouteImport.update({
  id: '/console_/callback',
  path: '/console/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleLoginIndexRoute = ConsoleLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleLoginRoute,
} as any)
const ConsoleLoginChannelsRoute = ConsoleLoginChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ConsoleLoginRoute,
} as any)
const ConsoleUsersIndexRoute = ConsoleUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersSubRoute = ConsoleUsersSubRouteImport.update({
  id: '/users/$sub',
  path: '/users/$sub',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/console': typeof ConsoleRouteWithChildren
  '/account/callback': typeof AccountCallbackRoute
  '/console/apis': typeof ConsoleApisRoute
  '/console/apps': typeof ConsoleAppsRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/login': typeof ConsoleLoginRouteWithChildren
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/callback': typeof ConsoleCallbackRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/login/channels': typeof ConsoleLoginChannelsRoute
  '/console/users/$sub': typeof ConsoleUsersSubRoute
  '/console/login/': typeof ConsoleLoginIndexRoute
  '/console/users/': typeof ConsoleUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/account/callback': typeof AccountCallbackRoute
  '/console/apis': typeof ConsoleApisRoute
  '/console/apps': typeof ConsoleAppsRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/callback': typeof ConsoleCallbackRoute
  '/console': typeof ConsoleIndexRoute
  '/console/login/channels': typeof ConsoleLoginChannelsRoute
  '/console/users/$sub': typeof ConsoleUsersSubRoute
  '/console/login': typeof ConsoleLoginIndexRoute
  '/console/users': typeof ConsoleUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/console': typeof ConsoleRouteWithChildren
  '/account_/callback': typeof AccountCallbackRoute
  '/console/apis': typeof ConsoleApisRoute
  '/console/apps': typeof ConsoleAppsRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/login': typeof ConsoleLoginRouteWithChildren
  '/console/settings': typeof ConsoleSettingsRoute
  '/console_/callback': typeof ConsoleCallbackRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/login/channels': typeof ConsoleLoginChannelsRoute
  '/console/users/$sub': typeof ConsoleUsersSubRoute
  '/console/login/': typeof ConsoleLoginIndexRoute
  '/console/users/': typeof ConsoleUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/account'
    | '/console'
    | '/account/callback'
    | '/console/apis'
    | '/console/apps'
    | '/console/audit'
    | '/console/login'
    | '/console/settings'
    | '/console/callback'
    | '/console/'
    | '/console/login/channels'
    | '/console/users/$sub'
    | '/console/login/'
    | '/console/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/account'
    | '/account/callback'
    | '/console/apis'
    | '/console/apps'
    | '/console/audit'
    | '/console/settings'
    | '/console/callback'
    | '/console'
    | '/console/login/channels'
    | '/console/users/$sub'
    | '/console/login'
    | '/console/users'
  id:
    | '__root__'
    | '/$'
    | '/account'
    | '/console'
    | '/account_/callback'
    | '/console/apis'
    | '/console/apps'
    | '/console/audit'
    | '/console/login'
    | '/console/settings'
    | '/console_/callback'
    | '/console/'
    | '/console/login/channels'
    | '/console/users/$sub'
    | '/console/login/'
    | '/console/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  AccountCallbackRoute: typeof AccountCallbackRoute
  ConsoleCallbackRoute: typeof ConsoleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/callback': {
      id: '/account_/callback'
      path: '/account/callback'
      fullPath: '/account/callback'
      preLoaderRoute: typeof AccountCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apis': {
      id: '/console/apis'
      path: '/apis'
      fullPath: '/console/apis'
      preLoaderRoute: typeof ConsoleApisRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apps': {
      id: '/console/apps'
      path: '/apps'
      fullPath: '/console/apps'
      preLoaderRoute: typeof ConsoleAppsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/audit': {
      id: '/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/login': {
      id: '/console/login'
      path: '/login'
      fullPath: '/console/login'
      preLoaderRoute: typeof ConsoleLoginRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console_/callback': {
      id: '/console_/callback'
      path: '/console/callback'
      fullPath: '/console/callback'
      preLoaderRoute: typeof ConsoleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/login/': {
      id: '/console/login/'
      path: '/'
      fullPath: '/console/login/'
      preLoaderRoute: typeof ConsoleLoginIndexRouteImport
      parentRoute: typeof ConsoleLoginRoute
    }
    '/console/login/channels': {
      id: '/console/login/channels'
      path: '/channels'
      fullPath: '/console/login/channels'
      preLoaderRoute: typeof ConsoleLoginChannelsRouteImport
      parentRoute: typeof ConsoleLoginRoute
    }
    '/console/users/': {
      id: '/console/users/'
      path: '/users'
      fullPath: '/console/users/'
      preLoaderRoute: typeof ConsoleUsersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/users/$sub': {
      id: '/console/users/$sub'
      path: '/users/$sub'
      fullPath: '/console/users/$sub'
      preLoaderRoute: typeof ConsoleUsersSubRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleLoginRouteChildren {
  ConsoleLoginChannelsRoute: typeof ConsoleLoginChannelsRoute
  ConsoleLoginIndexRoute: typeof ConsoleLoginIndexRoute
}

const ConsoleLoginRouteChildren: ConsoleLoginRouteChildren = {
  ConsoleLoginChannelsRoute: ConsoleLoginChannelsRoute,
  ConsoleLoginIndexRoute: ConsoleLoginIndexRoute,
}

const ConsoleLoginRouteWithChildren = ConsoleLoginRoute._addFileChildren(
  ConsoleLoginRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleApisRoute: typeof ConsoleApisRoute
  ConsoleAppsRoute: typeof ConsoleAppsRoute
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleLoginRoute: typeof ConsoleLoginRouteWithChildren
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleUsersSubRoute: typeof ConsoleUsersSubRoute
  ConsoleUsersIndexRoute: typeof ConsoleUsersIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleApisRoute: ConsoleApisRoute,
  ConsoleAppsRoute: ConsoleAppsRoute,
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleLoginRoute: ConsoleLoginRouteWithChildren,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleUsersSubRoute: ConsoleUsersSubRoute,
  ConsoleUsersIndexRoute: ConsoleUsersIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  AccountCallbackRoute: AccountCallbackRoute,
  ConsoleCallbackRoute: ConsoleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
